// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ChainConfigInitParameters struct {

	// Each node in the delivery chain. See nodes below.
	Nodes []NodesInitParameters `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// Execution sequence relationship between delivery chain nodes. See routers below.
	Routers []RoutersInitParameters `json:"routers,omitempty" tf:"routers,omitempty"`
}

type ChainConfigObservation struct {

	// Each node in the delivery chain. See nodes below.
	Nodes []NodesObservation `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// Execution sequence relationship between delivery chain nodes. See routers below.
	Routers []RoutersObservation `json:"routers,omitempty" tf:"routers,omitempty"`
}

type ChainConfigParameters struct {

	// Each node in the delivery chain. See nodes below.
	// +kubebuilder:validation:Optional
	Nodes []NodesParameters `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// Execution sequence relationship between delivery chain nodes. See routers below.
	// +kubebuilder:validation:Optional
	Routers []RoutersParameters `json:"routers,omitempty" tf:"routers,omitempty"`
}

type ChainInitParameters struct {

	// The configuration of delivery chain. See chain_config below. NOTE: This parameter must specify the correct value, otherwise the created resource will be incorrect.
	ChainConfig []ChainConfigInitParameters `json:"chainConfig,omitempty" tf:"chain_config,omitempty"`

	// The name of delivery chain. The length of the name is 1-64 characters, lowercase English letters and numbers, and the separators "_", "-", "." can be used, noted that the separator cannot be at the first or last position.
	ChainName *string `json:"chainName,omitempty" tf:"chain_name,omitempty"`

	// The description delivery chain.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of CR Enterprise Edition instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The name of CR Enterprise Edition repository. NOTE: This parameter must specify a correct value, otherwise the created resource will be incorrect.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeRepo
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// Reference to a EeRepo in cr to populate repoName.
	// +kubebuilder:validation:Optional
	RepoNameRef *v1.Reference `json:"repoNameRef,omitempty" tf:"-"`

	// Selector for a EeRepo in cr to populate repoName.
	// +kubebuilder:validation:Optional
	RepoNameSelector *v1.Selector `json:"repoNameSelector,omitempty" tf:"-"`

	// The name of CR Enterprise Edition namespace. NOTE: This parameter must specify the correct value, otherwise the created resource will be incorrect.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	RepoNamespaceName *string `json:"repoNamespaceName,omitempty" tf:"repo_namespace_name,omitempty"`

	// Reference to a EeNamespace in cr to populate repoNamespaceName.
	// +kubebuilder:validation:Optional
	RepoNamespaceNameRef *v1.Reference `json:"repoNamespaceNameRef,omitempty" tf:"-"`

	// Selector for a EeNamespace in cr to populate repoNamespaceName.
	// +kubebuilder:validation:Optional
	RepoNamespaceNameSelector *v1.Selector `json:"repoNamespaceNameSelector,omitempty" tf:"-"`
}

type ChainObservation struct {

	// The configuration of delivery chain. See chain_config below. NOTE: This parameter must specify the correct value, otherwise the created resource will be incorrect.
	ChainConfig []ChainConfigObservation `json:"chainConfig,omitempty" tf:"chain_config,omitempty"`

	// Delivery chain ID.
	ChainID *string `json:"chainId,omitempty" tf:"chain_id,omitempty"`

	// The name of delivery chain. The length of the name is 1-64 characters, lowercase English letters and numbers, and the separators "_", "-", "." can be used, noted that the separator cannot be at the first or last position.
	ChainName *string `json:"chainName,omitempty" tf:"chain_name,omitempty"`

	// The description delivery chain.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The resource ID of Chain. The value formats as <instance_id>:<chain_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of CR Enterprise Edition instance.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The name of CR Enterprise Edition repository. NOTE: This parameter must specify a correct value, otherwise the created resource will be incorrect.
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// The name of CR Enterprise Edition namespace. NOTE: This parameter must specify the correct value, otherwise the created resource will be incorrect.
	RepoNamespaceName *string `json:"repoNamespaceName,omitempty" tf:"repo_namespace_name,omitempty"`
}

type ChainParameters struct {

	// The configuration of delivery chain. See chain_config below. NOTE: This parameter must specify the correct value, otherwise the created resource will be incorrect.
	// +kubebuilder:validation:Optional
	ChainConfig []ChainConfigParameters `json:"chainConfig,omitempty" tf:"chain_config,omitempty"`

	// The name of delivery chain. The length of the name is 1-64 characters, lowercase English letters and numbers, and the separators "_", "-", "." can be used, noted that the separator cannot be at the first or last position.
	// +kubebuilder:validation:Optional
	ChainName *string `json:"chainName,omitempty" tf:"chain_name,omitempty"`

	// The description delivery chain.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of CR Enterprise Edition instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The name of CR Enterprise Edition repository. NOTE: This parameter must specify a correct value, otherwise the created resource will be incorrect.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeRepo
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// Reference to a EeRepo in cr to populate repoName.
	// +kubebuilder:validation:Optional
	RepoNameRef *v1.Reference `json:"repoNameRef,omitempty" tf:"-"`

	// Selector for a EeRepo in cr to populate repoName.
	// +kubebuilder:validation:Optional
	RepoNameSelector *v1.Selector `json:"repoNameSelector,omitempty" tf:"-"`

	// The name of CR Enterprise Edition namespace. NOTE: This parameter must specify the correct value, otherwise the created resource will be incorrect.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	RepoNamespaceName *string `json:"repoNamespaceName,omitempty" tf:"repo_namespace_name,omitempty"`

	// Reference to a EeNamespace in cr to populate repoNamespaceName.
	// +kubebuilder:validation:Optional
	RepoNamespaceNameRef *v1.Reference `json:"repoNamespaceNameRef,omitempty" tf:"-"`

	// Selector for a EeNamespace in cr to populate repoNamespaceName.
	// +kubebuilder:validation:Optional
	RepoNamespaceNameSelector *v1.Selector `json:"repoNamespaceNameSelector,omitempty" tf:"-"`
}

type DenyPolicyInitParameters struct {

	// The action of trigger blocking. Valid values: BLOCK, BLOCK_RETAG, BLOCK_DELETE_TAG. While Block means block the delivery chain from continuing to execute, BLOCK_RETAG means block overwriting push image tag, BLOCK_DELETE_TAG means block deletion of mirror tags.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// The count of scanning vulnerabilities that triggers blocking.
	IssueCount *string `json:"issueCount,omitempty" tf:"issue_count,omitempty"`

	// The level of scanning vulnerability that triggers blocking. Valid values: LOW, MEDIUM, HIGH, UNKNOWN.
	IssueLevel *string `json:"issueLevel,omitempty" tf:"issue_level,omitempty"`

	// The logic of trigger blocking. Valid values: AND, OR.
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`
}

type DenyPolicyObservation struct {

	// The action of trigger blocking. Valid values: BLOCK, BLOCK_RETAG, BLOCK_DELETE_TAG. While Block means block the delivery chain from continuing to execute, BLOCK_RETAG means block overwriting push image tag, BLOCK_DELETE_TAG means block deletion of mirror tags.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// The count of scanning vulnerabilities that triggers blocking.
	IssueCount *string `json:"issueCount,omitempty" tf:"issue_count,omitempty"`

	// The level of scanning vulnerability that triggers blocking. Valid values: LOW, MEDIUM, HIGH, UNKNOWN.
	IssueLevel *string `json:"issueLevel,omitempty" tf:"issue_level,omitempty"`

	// The logic of trigger blocking. Valid values: AND, OR.
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`
}

type DenyPolicyParameters struct {

	// The action of trigger blocking. Valid values: BLOCK, BLOCK_RETAG, BLOCK_DELETE_TAG. While Block means block the delivery chain from continuing to execute, BLOCK_RETAG means block overwriting push image tag, BLOCK_DELETE_TAG means block deletion of mirror tags.
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// The count of scanning vulnerabilities that triggers blocking.
	// +kubebuilder:validation:Optional
	IssueCount *string `json:"issueCount,omitempty" tf:"issue_count,omitempty"`

	// The level of scanning vulnerability that triggers blocking. Valid values: LOW, MEDIUM, HIGH, UNKNOWN.
	// +kubebuilder:validation:Optional
	IssueLevel *string `json:"issueLevel,omitempty" tf:"issue_level,omitempty"`

	// The logic of trigger blocking. Valid values: AND, OR.
	// +kubebuilder:validation:Optional
	Logic *string `json:"logic,omitempty" tf:"logic,omitempty"`
}

type FromInitParameters struct {

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type FromObservation struct {

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type FromParameters struct {

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	// +kubebuilder:validation:Optional
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type NodeConfigInitParameters struct {

	// Blocking rules for scanning nodes in delivery chain nodes. See deny_policy below. Note: When node_name is VULNERABILITY_SCANNING, the parameters in deny_policy need to be filled in.
	DenyPolicy []DenyPolicyInitParameters `json:"denyPolicy,omitempty" tf:"deny_policy,omitempty"`
}

type NodeConfigObservation struct {

	// Blocking rules for scanning nodes in delivery chain nodes. See deny_policy below. Note: When node_name is VULNERABILITY_SCANNING, the parameters in deny_policy need to be filled in.
	DenyPolicy []DenyPolicyObservation `json:"denyPolicy,omitempty" tf:"deny_policy,omitempty"`
}

type NodeConfigParameters struct {

	// Blocking rules for scanning nodes in delivery chain nodes. See deny_policy below. Note: When node_name is VULNERABILITY_SCANNING, the parameters in deny_policy need to be filled in.
	// +kubebuilder:validation:Optional
	DenyPolicy []DenyPolicyParameters `json:"denyPolicy,omitempty" tf:"deny_policy,omitempty"`
}

type NodesInitParameters struct {

	// Whether to enable the delivery chain node. Valid values: true, false.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The configuration of delivery chain node. See node_config below.
	NodeConfig []NodeConfigInitParameters `json:"nodeConfig,omitempty" tf:"node_config,omitempty"`

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type NodesObservation struct {

	// Whether to enable the delivery chain node. Valid values: true, false.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The configuration of delivery chain node. See node_config below.
	NodeConfig []NodeConfigObservation `json:"nodeConfig,omitempty" tf:"node_config,omitempty"`

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type NodesParameters struct {

	// Whether to enable the delivery chain node. Valid values: true, false.
	// +kubebuilder:validation:Optional
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The configuration of delivery chain node. See node_config below.
	// +kubebuilder:validation:Optional
	NodeConfig []NodeConfigParameters `json:"nodeConfig,omitempty" tf:"node_config,omitempty"`

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	// +kubebuilder:validation:Optional
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type RoutersInitParameters struct {

	// Source node. See from below.
	From []FromInitParameters `json:"from,omitempty" tf:"from,omitempty"`

	// Destination node. See to below.
	To []ToInitParameters `json:"to,omitempty" tf:"to,omitempty"`
}

type RoutersObservation struct {

	// Source node. See from below.
	From []FromObservation `json:"from,omitempty" tf:"from,omitempty"`

	// Destination node. See to below.
	To []ToObservation `json:"to,omitempty" tf:"to,omitempty"`
}

type RoutersParameters struct {

	// Source node. See from below.
	// +kubebuilder:validation:Optional
	From []FromParameters `json:"from,omitempty" tf:"from,omitempty"`

	// Destination node. See to below.
	// +kubebuilder:validation:Optional
	To []ToParameters `json:"to,omitempty" tf:"to,omitempty"`
}

type ToInitParameters struct {

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type ToObservation struct {

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

type ToParameters struct {

	// The name of node. Valid values: DOCKER_IMAGE_BUILD, DOCKER_IMAGE_PUSH, VULNERABILITY_SCANNING, ACTIVATE_REPLICATION, TRIGGER, SNAPSHOT, TRIGGER_SNAPSHOT.
	// +kubebuilder:validation:Optional
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`
}

// ChainSpec defines the desired state of Chain
type ChainSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ChainParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ChainInitParameters `json:"initProvider,omitempty"`
}

// ChainStatus defines the observed state of Chain.
type ChainStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ChainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Chain is the Schema for the Chains API. Provides a Alicloud CR Chain resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Chain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.chainName) || (has(self.initProvider) && has(self.initProvider.chainName))",message="spec.forProvider.chainName is a required parameter"
	Spec   ChainSpec   `json:"spec"`
	Status ChainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ChainList contains a list of Chains
type ChainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Chain `json:"items"`
}

// Repository type metadata.
var (
	Chain_Kind             = "Chain"
	Chain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Chain_Kind}.String()
	Chain_KindAPIVersion   = Chain_Kind + "." + CRDGroupVersion.String()
	Chain_GroupVersionKind = CRDGroupVersion.WithKind(Chain_Kind)
)

func init() {
	SchemeBuilder.Register(&Chain{}, &ChainList{})
}
