// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EeSyncRuleInitParameters struct {

	// The ID of the Container Registry source instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The namespace name of the source instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	NamespaceName *string `json:"namespaceName,omitempty" tf:"namespace_name,omitempty"`

	// Reference to a EeNamespace in cr to populate namespaceName.
	// +kubebuilder:validation:Optional
	NamespaceNameRef *v1.Reference `json:"namespaceNameRef,omitempty" tf:"-"`

	// Selector for a EeNamespace in cr to populate namespaceName.
	// +kubebuilder:validation:Optional
	NamespaceNameSelector *v1.Selector `json:"namespaceNameSelector,omitempty" tf:"-"`

	// The image repository name of the source instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeRepo
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// Reference to a EeRepo in cr to populate repoName.
	// +kubebuilder:validation:Optional
	RepoNameRef *v1.Reference `json:"repoNameRef,omitempty" tf:"-"`

	// Selector for a EeRepo in cr to populate repoName.
	// +kubebuilder:validation:Optional
	RepoNameSelector *v1.Selector `json:"repoNameSelector,omitempty" tf:"-"`

	// The name of the sync rule.
	SyncRuleName *string `json:"syncRuleName,omitempty" tf:"sync_rule_name,omitempty"`

	// The synchronization scope. Valid values:
	SyncScope *string `json:"syncScope,omitempty" tf:"sync_scope,omitempty"`

	// The policy configured to trigger the synchronization rule. Default value: PASSIVE. Valid values:
	SyncTrigger *string `json:"syncTrigger,omitempty" tf:"sync_trigger,omitempty"`

	// The regular expression used to filter image tags.
	TagFilter *string `json:"tagFilter,omitempty" tf:"tag_filter,omitempty"`

	// The ID of the destination instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	TargetInstanceID *string `json:"targetInstanceId,omitempty" tf:"target_instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate targetInstanceId.
	// +kubebuilder:validation:Optional
	TargetInstanceIDRef *v1.Reference `json:"targetInstanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate targetInstanceId.
	// +kubebuilder:validation:Optional
	TargetInstanceIDSelector *v1.Selector `json:"targetInstanceIdSelector,omitempty" tf:"-"`

	// The namespace name of the destination instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	TargetNamespaceName *string `json:"targetNamespaceName,omitempty" tf:"target_namespace_name,omitempty"`

	// Reference to a EeNamespace in cr to populate targetNamespaceName.
	// +kubebuilder:validation:Optional
	TargetNamespaceNameRef *v1.Reference `json:"targetNamespaceNameRef,omitempty" tf:"-"`

	// Selector for a EeNamespace in cr to populate targetNamespaceName.
	// +kubebuilder:validation:Optional
	TargetNamespaceNameSelector *v1.Selector `json:"targetNamespaceNameSelector,omitempty" tf:"-"`

	// The region ID of the destination instance.
	TargetRegionID *string `json:"targetRegionId,omitempty" tf:"target_region_id,omitempty"`

	// The image repository name of the destination instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeRepo
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	TargetRepoName *string `json:"targetRepoName,omitempty" tf:"target_repo_name,omitempty"`

	// Reference to a EeRepo in cr to populate targetRepoName.
	// +kubebuilder:validation:Optional
	TargetRepoNameRef *v1.Reference `json:"targetRepoNameRef,omitempty" tf:"-"`

	// Selector for a EeRepo in cr to populate targetRepoName.
	// +kubebuilder:validation:Optional
	TargetRepoNameSelector *v1.Selector `json:"targetRepoNameSelector,omitempty" tf:"-"`

	// The UID of the account to which the target instance belongs.
	TargetUserID *string `json:"targetUserId,omitempty" tf:"target_user_id,omitempty"`
}

type EeSyncRuleObservation struct {

	// (Available since v1.240.0) The time when the synchronization rule was created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// It formats as <instance_id>:<namespace_name>:<repo_sync_rule_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the Container Registry source instance.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The namespace name of the source instance.
	NamespaceName *string `json:"namespaceName,omitempty" tf:"namespace_name,omitempty"`

	// (Available since v1.240.0) The region ID of the source instance.
	RegionID *string `json:"regionId,omitempty" tf:"region_id,omitempty"`

	// The image repository name of the source instance.
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// (Available since v1.240.0) The ID of the synchronization rule.
	RepoSyncRuleID *string `json:"repoSyncRuleId,omitempty" tf:"repo_sync_rule_id,omitempty"`

	// (Deprecated since v1.240.0) Field rule_id has been deprecated from provider version 1.240.0. New field repo_sync_rule_id instead.
	RuleID *string `json:"ruleId,omitempty" tf:"rule_id,omitempty"`

	// The synchronization direction.
	SyncDirection *string `json:"syncDirection,omitempty" tf:"sync_direction,omitempty"`

	// The name of the sync rule.
	SyncRuleName *string `json:"syncRuleName,omitempty" tf:"sync_rule_name,omitempty"`

	// The synchronization scope. Valid values:
	SyncScope *string `json:"syncScope,omitempty" tf:"sync_scope,omitempty"`

	// The policy configured to trigger the synchronization rule. Default value: PASSIVE. Valid values:
	SyncTrigger *string `json:"syncTrigger,omitempty" tf:"sync_trigger,omitempty"`

	// The regular expression used to filter image tags.
	TagFilter *string `json:"tagFilter,omitempty" tf:"tag_filter,omitempty"`

	// The ID of the destination instance.
	TargetInstanceID *string `json:"targetInstanceId,omitempty" tf:"target_instance_id,omitempty"`

	// The namespace name of the destination instance.
	TargetNamespaceName *string `json:"targetNamespaceName,omitempty" tf:"target_namespace_name,omitempty"`

	// The region ID of the destination instance.
	TargetRegionID *string `json:"targetRegionId,omitempty" tf:"target_region_id,omitempty"`

	// The image repository name of the destination instance.
	TargetRepoName *string `json:"targetRepoName,omitempty" tf:"target_repo_name,omitempty"`

	// The UID of the account to which the target instance belongs.
	TargetUserID *string `json:"targetUserId,omitempty" tf:"target_user_id,omitempty"`
}

type EeSyncRuleParameters struct {

	// The ID of the Container Registry source instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The namespace name of the source instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	NamespaceName *string `json:"namespaceName,omitempty" tf:"namespace_name,omitempty"`

	// Reference to a EeNamespace in cr to populate namespaceName.
	// +kubebuilder:validation:Optional
	NamespaceNameRef *v1.Reference `json:"namespaceNameRef,omitempty" tf:"-"`

	// Selector for a EeNamespace in cr to populate namespaceName.
	// +kubebuilder:validation:Optional
	NamespaceNameSelector *v1.Selector `json:"namespaceNameSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The image repository name of the source instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeRepo
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	RepoName *string `json:"repoName,omitempty" tf:"repo_name,omitempty"`

	// Reference to a EeRepo in cr to populate repoName.
	// +kubebuilder:validation:Optional
	RepoNameRef *v1.Reference `json:"repoNameRef,omitempty" tf:"-"`

	// Selector for a EeRepo in cr to populate repoName.
	// +kubebuilder:validation:Optional
	RepoNameSelector *v1.Selector `json:"repoNameSelector,omitempty" tf:"-"`

	// The name of the sync rule.
	// +kubebuilder:validation:Optional
	SyncRuleName *string `json:"syncRuleName,omitempty" tf:"sync_rule_name,omitempty"`

	// The synchronization scope. Valid values:
	// +kubebuilder:validation:Optional
	SyncScope *string `json:"syncScope,omitempty" tf:"sync_scope,omitempty"`

	// The policy configured to trigger the synchronization rule. Default value: PASSIVE. Valid values:
	// +kubebuilder:validation:Optional
	SyncTrigger *string `json:"syncTrigger,omitempty" tf:"sync_trigger,omitempty"`

	// The regular expression used to filter image tags.
	// +kubebuilder:validation:Optional
	TagFilter *string `json:"tagFilter,omitempty" tf:"tag_filter,omitempty"`

	// The ID of the destination instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	TargetInstanceID *string `json:"targetInstanceId,omitempty" tf:"target_instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate targetInstanceId.
	// +kubebuilder:validation:Optional
	TargetInstanceIDRef *v1.Reference `json:"targetInstanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate targetInstanceId.
	// +kubebuilder:validation:Optional
	TargetInstanceIDSelector *v1.Selector `json:"targetInstanceIdSelector,omitempty" tf:"-"`

	// The namespace name of the destination instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeNamespace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	TargetNamespaceName *string `json:"targetNamespaceName,omitempty" tf:"target_namespace_name,omitempty"`

	// Reference to a EeNamespace in cr to populate targetNamespaceName.
	// +kubebuilder:validation:Optional
	TargetNamespaceNameRef *v1.Reference `json:"targetNamespaceNameRef,omitempty" tf:"-"`

	// Selector for a EeNamespace in cr to populate targetNamespaceName.
	// +kubebuilder:validation:Optional
	TargetNamespaceNameSelector *v1.Selector `json:"targetNamespaceNameSelector,omitempty" tf:"-"`

	// The region ID of the destination instance.
	// +kubebuilder:validation:Optional
	TargetRegionID *string `json:"targetRegionId,omitempty" tf:"target_region_id,omitempty"`

	// The image repository name of the destination instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/cr/v1alpha1.EeRepo
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	TargetRepoName *string `json:"targetRepoName,omitempty" tf:"target_repo_name,omitempty"`

	// Reference to a EeRepo in cr to populate targetRepoName.
	// +kubebuilder:validation:Optional
	TargetRepoNameRef *v1.Reference `json:"targetRepoNameRef,omitempty" tf:"-"`

	// Selector for a EeRepo in cr to populate targetRepoName.
	// +kubebuilder:validation:Optional
	TargetRepoNameSelector *v1.Selector `json:"targetRepoNameSelector,omitempty" tf:"-"`

	// The UID of the account to which the target instance belongs.
	// +kubebuilder:validation:Optional
	TargetUserID *string `json:"targetUserId,omitempty" tf:"target_user_id,omitempty"`
}

// EeSyncRuleSpec defines the desired state of EeSyncRule
type EeSyncRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EeSyncRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EeSyncRuleInitParameters `json:"initProvider,omitempty"`
}

// EeSyncRuleStatus defines the observed state of EeSyncRule.
type EeSyncRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EeSyncRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EeSyncRule is the Schema for the EeSyncRules API. Provides a Alicloud Container Registry Sync Rule resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type EeSyncRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tagFilter) || (has(self.initProvider) && has(self.initProvider.tagFilter))",message="spec.forProvider.tagFilter is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetRegionId) || (has(self.initProvider) && has(self.initProvider.targetRegionId))",message="spec.forProvider.targetRegionId is a required parameter"
	Spec   EeSyncRuleSpec   `json:"spec"`
	Status EeSyncRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EeSyncRuleList contains a list of EeSyncRules
type EeSyncRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EeSyncRule `json:"items"`
}

// Repository type metadata.
var (
	EeSyncRule_Kind             = "EeSyncRule"
	EeSyncRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EeSyncRule_Kind}.String()
	EeSyncRule_KindAPIVersion   = EeSyncRule_Kind + "." + CRDGroupVersion.String()
	EeSyncRule_GroupVersionKind = CRDGroupVersion.WithKind(EeSyncRule_Kind)
)

func init() {
	SchemeBuilder.Register(&EeSyncRule{}, &EeSyncRuleList{})
}
