// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Chain) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ChartNamespace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ChartRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EeInstance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EeNamespace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EeRepo) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EeSyncRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EndpointACLPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RegistryNamespace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Repo) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ScanRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StorageDomainRoutingRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VPCEndpointLinkedVPC) Hub() {}
