apiVersion: oos.alibabacloud.m.crossplane.io/v1alpha1
kind: Execution
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/execution
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    description: From TF Test
    parameters: "\t\t\t\t{\"Status\":\"Running\"}\n"
    region: cn-beijing
    tags:
      Created: TF
      For: execution Test
    templateNameSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: oos.alibabacloud.m.crossplane.io/v1alpha1
kind: Template
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/execution
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    content: |2
        {
          "FormatVersion": "OOS-2019-06-01",
          "Description": "Update Describe instances of given status",
          "Parameters":{
            "Status":{
              "Type": "String",
              "Description": "(Required) The status of the Ecs instance."
            }
          },
          "Tasks": [
            {
              "Properties" :{
                "Parameters":{
                  "Status": "{{ Status }}"
                },
                "API": "DescribeInstances",
                "Service": "Ecs"
              },
              "Name": "foo",
              "Action": "ACS::ExecuteApi"
            }]
        }
    region: cn-beijing
    tags:
      Created: TF
      For: acceptance Test
    templateName: tf-example-name-${random_integer.default.result}
    versionName: example
