// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ConfluentConfigInitParameters struct {

	// The number of CPU cores of Connect.
	ConnectCu *float64 `json:"connectCu,omitempty" tf:"connect_cu,omitempty"`

	// The number of replicas of Connect.
	ConnectReplica *float64 `json:"connectReplica,omitempty" tf:"connect_replica,omitempty"`

	// The number of CPU cores of Control Center.
	ControlCenterCu *float64 `json:"controlCenterCu,omitempty" tf:"control_center_cu,omitempty"`

	// The number of replicas of Control Center.
	ControlCenterReplica *float64 `json:"controlCenterReplica,omitempty" tf:"control_center_replica,omitempty"`

	// The disk capacity of Control Center.
	ControlCenterStorage *float64 `json:"controlCenterStorage,omitempty" tf:"control_center_storage,omitempty"`

	// The number of CPU cores of the Kafka broker.
	KafkaCu *float64 `json:"kafkaCu,omitempty" tf:"kafka_cu,omitempty"`

	// The number of replicas of the Kafka broker.
	KafkaReplica *float64 `json:"kafkaReplica,omitempty" tf:"kafka_replica,omitempty"`

	// The number of CPU cores of Kafka Rest Proxy.
	KafkaRestProxyCu *float64 `json:"kafkaRestProxyCu,omitempty" tf:"kafka_rest_proxy_cu,omitempty"`

	// The number of replicas of Kafka Rest Proxy.
	KafkaRestProxyReplica *float64 `json:"kafkaRestProxyReplica,omitempty" tf:"kafka_rest_proxy_replica,omitempty"`

	// The disk capacity of the Kafka broker.
	KafkaStorage *float64 `json:"kafkaStorage,omitempty" tf:"kafka_storage,omitempty"`

	// The number of CPU cores of ksqlDB.
	KsqlCu *float64 `json:"ksqlCu,omitempty" tf:"ksql_cu,omitempty"`

	// The number of replicas of ksqlDB.
	KsqlReplica *float64 `json:"ksqlReplica,omitempty" tf:"ksql_replica,omitempty"`

	// The disk capacity of ksqlDB.
	KsqlStorage *float64 `json:"ksqlStorage,omitempty" tf:"ksql_storage,omitempty"`

	// The number of CPU cores of Schema Registry.
	SchemaRegistryCu *float64 `json:"schemaRegistryCu,omitempty" tf:"schema_registry_cu,omitempty"`

	// The number of replicas of Schema Registry.
	SchemaRegistryReplica *float64 `json:"schemaRegistryReplica,omitempty" tf:"schema_registry_replica,omitempty"`

	// The number of CPU cores of ZooKeeper.
	ZookeeperCu *float64 `json:"zookeeperCu,omitempty" tf:"zookeeper_cu,omitempty"`

	// The number of replicas of ZooKeeper.
	ZookeeperReplica *float64 `json:"zookeeperReplica,omitempty" tf:"zookeeper_replica,omitempty"`

	// The disk capacity of ZooKeeper.
	ZookeeperStorage *float64 `json:"zookeeperStorage,omitempty" tf:"zookeeper_storage,omitempty"`
}

type ConfluentConfigObservation struct {

	// The number of CPU cores of Connect.
	ConnectCu *float64 `json:"connectCu,omitempty" tf:"connect_cu,omitempty"`

	// The number of replicas of Connect.
	ConnectReplica *float64 `json:"connectReplica,omitempty" tf:"connect_replica,omitempty"`

	// The number of CPU cores of Control Center.
	ControlCenterCu *float64 `json:"controlCenterCu,omitempty" tf:"control_center_cu,omitempty"`

	// The number of replicas of Control Center.
	ControlCenterReplica *float64 `json:"controlCenterReplica,omitempty" tf:"control_center_replica,omitempty"`

	// The disk capacity of Control Center.
	ControlCenterStorage *float64 `json:"controlCenterStorage,omitempty" tf:"control_center_storage,omitempty"`

	// The number of CPU cores of the Kafka broker.
	KafkaCu *float64 `json:"kafkaCu,omitempty" tf:"kafka_cu,omitempty"`

	// The number of replicas of the Kafka broker.
	KafkaReplica *float64 `json:"kafkaReplica,omitempty" tf:"kafka_replica,omitempty"`

	// The number of CPU cores of Kafka Rest Proxy.
	KafkaRestProxyCu *float64 `json:"kafkaRestProxyCu,omitempty" tf:"kafka_rest_proxy_cu,omitempty"`

	// The number of replicas of Kafka Rest Proxy.
	KafkaRestProxyReplica *float64 `json:"kafkaRestProxyReplica,omitempty" tf:"kafka_rest_proxy_replica,omitempty"`

	// The disk capacity of the Kafka broker.
	KafkaStorage *float64 `json:"kafkaStorage,omitempty" tf:"kafka_storage,omitempty"`

	// The number of CPU cores of ksqlDB.
	KsqlCu *float64 `json:"ksqlCu,omitempty" tf:"ksql_cu,omitempty"`

	// The number of replicas of ksqlDB.
	KsqlReplica *float64 `json:"ksqlReplica,omitempty" tf:"ksql_replica,omitempty"`

	// The disk capacity of ksqlDB.
	KsqlStorage *float64 `json:"ksqlStorage,omitempty" tf:"ksql_storage,omitempty"`

	// The number of CPU cores of Schema Registry.
	SchemaRegistryCu *float64 `json:"schemaRegistryCu,omitempty" tf:"schema_registry_cu,omitempty"`

	// The number of replicas of Schema Registry.
	SchemaRegistryReplica *float64 `json:"schemaRegistryReplica,omitempty" tf:"schema_registry_replica,omitempty"`

	// The number of CPU cores of ZooKeeper.
	ZookeeperCu *float64 `json:"zookeeperCu,omitempty" tf:"zookeeper_cu,omitempty"`

	// The number of replicas of ZooKeeper.
	ZookeeperReplica *float64 `json:"zookeeperReplica,omitempty" tf:"zookeeper_replica,omitempty"`

	// The disk capacity of ZooKeeper.
	ZookeeperStorage *float64 `json:"zookeeperStorage,omitempty" tf:"zookeeper_storage,omitempty"`
}

type ConfluentConfigParameters struct {

	// The number of CPU cores of Connect.
	// +kubebuilder:validation:Optional
	ConnectCu *float64 `json:"connectCu,omitempty" tf:"connect_cu,omitempty"`

	// The number of replicas of Connect.
	// +kubebuilder:validation:Optional
	ConnectReplica *float64 `json:"connectReplica,omitempty" tf:"connect_replica,omitempty"`

	// The number of CPU cores of Control Center.
	// +kubebuilder:validation:Optional
	ControlCenterCu *float64 `json:"controlCenterCu,omitempty" tf:"control_center_cu,omitempty"`

	// The number of replicas of Control Center.
	// +kubebuilder:validation:Optional
	ControlCenterReplica *float64 `json:"controlCenterReplica,omitempty" tf:"control_center_replica,omitempty"`

	// The disk capacity of Control Center.
	// +kubebuilder:validation:Optional
	ControlCenterStorage *float64 `json:"controlCenterStorage,omitempty" tf:"control_center_storage,omitempty"`

	// The number of CPU cores of the Kafka broker.
	// +kubebuilder:validation:Optional
	KafkaCu *float64 `json:"kafkaCu,omitempty" tf:"kafka_cu,omitempty"`

	// The number of replicas of the Kafka broker.
	// +kubebuilder:validation:Optional
	KafkaReplica *float64 `json:"kafkaReplica,omitempty" tf:"kafka_replica,omitempty"`

	// The number of CPU cores of Kafka Rest Proxy.
	// +kubebuilder:validation:Optional
	KafkaRestProxyCu *float64 `json:"kafkaRestProxyCu,omitempty" tf:"kafka_rest_proxy_cu,omitempty"`

	// The number of replicas of Kafka Rest Proxy.
	// +kubebuilder:validation:Optional
	KafkaRestProxyReplica *float64 `json:"kafkaRestProxyReplica,omitempty" tf:"kafka_rest_proxy_replica,omitempty"`

	// The disk capacity of the Kafka broker.
	// +kubebuilder:validation:Optional
	KafkaStorage *float64 `json:"kafkaStorage,omitempty" tf:"kafka_storage,omitempty"`

	// The number of CPU cores of ksqlDB.
	// +kubebuilder:validation:Optional
	KsqlCu *float64 `json:"ksqlCu,omitempty" tf:"ksql_cu,omitempty"`

	// The number of replicas of ksqlDB.
	// +kubebuilder:validation:Optional
	KsqlReplica *float64 `json:"ksqlReplica,omitempty" tf:"ksql_replica,omitempty"`

	// The disk capacity of ksqlDB.
	// +kubebuilder:validation:Optional
	KsqlStorage *float64 `json:"ksqlStorage,omitempty" tf:"ksql_storage,omitempty"`

	// The number of CPU cores of Schema Registry.
	// +kubebuilder:validation:Optional
	SchemaRegistryCu *float64 `json:"schemaRegistryCu,omitempty" tf:"schema_registry_cu,omitempty"`

	// The number of replicas of Schema Registry.
	// +kubebuilder:validation:Optional
	SchemaRegistryReplica *float64 `json:"schemaRegistryReplica,omitempty" tf:"schema_registry_replica,omitempty"`

	// The number of CPU cores of ZooKeeper.
	// +kubebuilder:validation:Optional
	ZookeeperCu *float64 `json:"zookeeperCu,omitempty" tf:"zookeeper_cu,omitempty"`

	// The number of replicas of ZooKeeper.
	// +kubebuilder:validation:Optional
	ZookeeperReplica *float64 `json:"zookeeperReplica,omitempty" tf:"zookeeper_replica,omitempty"`

	// The disk capacity of ZooKeeper.
	// +kubebuilder:validation:Optional
	ZookeeperStorage *float64 `json:"zookeeperStorage,omitempty" tf:"zookeeper_storage,omitempty"`
}

type InstanceInitParameters struct {

	// The initial configurations of the ApsaraMQ for Kafka instance. The values must be valid JSON strings.
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// The configurations of Confluent. See confluent_config below.
	// -> NOTE: If instance_type is set to alikafka_confluent, confluent_config is required.
	ConfluentConfig []ConfluentConfigInitParameters `json:"confluentConfig,omitempty" tf:"confluent_config,omitempty"`

	// The number of partitions in a topic that is automatically created.
	DefaultTopicPartitionNum *float64 `json:"defaultTopicPartitionNum,omitempty" tf:"default_topic_partition_num,omitempty"`

	// The deployment type of the instance. NOTE: From version 1.161.0, this attribute supports to be updated. Valid values:
	DeployType *float64 `json:"deployType,omitempty" tf:"deploy_type,omitempty"`

	// The disk size of the instance. When modify this value, it only supports adjust to a greater value.
	// -> NOTE: If instance_type is set to alikafka, disk_size is required.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// The disk type of the instance. Valid values:
	DiskType *float64 `json:"diskType,omitempty" tf:"disk_type,omitempty"`

	// The max bandwidth of the instance. It will be ignored when deploy_type = 5. When modify this value, it only supports adjust to a greater value.
	EIPMax *float64 `json:"eipMax,omitempty" tf:"eip_max,omitempty"`

	// Specify whether to enable the flexible group creation feature. Default value: false. Valid values:
	EnableAutoGroup *bool `json:"enableAutoGroup,omitempty" tf:"enable_auto_group,omitempty"`

	// Specify whether to enable the automatic topic creation feature. Default value: disable. Valid values:
	EnableAutoTopic *string `json:"enableAutoTopic,omitempty" tf:"enable_auto_topic,omitempty"`

	// The type of the Instance. Default value: alikafka. Valid values:
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The max value of io of the instance. When modify this value, it only support adjust to a greater value.
	IoMax *float64 `json:"ioMax,omitempty" tf:"io_max,omitempty"`

	// The traffic specification of the instance. We recommend that you configure this parameter.
	IoMaxSpec *string `json:"ioMaxSpec,omitempty" tf:"io_max_spec,omitempty"`

	// The ID of the key that is used to encrypt data on standard SSDs in the region of the instance. For more information, see How to use it.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/kms/v1alpha1.Key
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// Reference to a Key in kms to populate kmsKeyId.
	// +kubebuilder:validation:Optional
	KMSKeyIDRef *v1.Reference `json:"kmsKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in kms to populate kmsKeyId.
	// +kubebuilder:validation:Optional
	KMSKeyIDSelector *v1.Selector `json:"kmsKeyIdSelector,omitempty" tf:"-"`

	// Name of your Kafka instance. The length should between 3 and 64 characters. If not set, will use instance id as instance name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The billing method of the instance. Default value: PostPaid. Valid values: PostPaid, PrePaid. When modify this value, it only support adjust from PostPaid to PrePaid.
	PaidType *string `json:"paidType,omitempty" tf:"paid_type,omitempty"`

	// The number of partitions.
	PartitionNum *float64 `json:"partitionNum,omitempty" tf:"partition_num,omitempty"`

	// The instance password. NOTE: If instance_type is set to alikafka_confluent, password is required.
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// The ID of the resource group. Note: Once you set a value of this property, you cannot set it to an empty string anymore.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The ID of security group for this instance. If the security group is empty, system will create a default one.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/ecs/v1alpha1.SecurityGroup
	SecurityGroup *string `json:"securityGroup,omitempty" tf:"security_group,omitempty"`

	// Reference to a SecurityGroup in ecs to populate securityGroup.
	// +kubebuilder:validation:Optional
	SecurityGroupRef *v1.Reference `json:"securityGroupRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in ecs to populate securityGroup.
	// +kubebuilder:validation:Optional
	SecurityGroupSelector *v1.Selector `json:"securityGroupSelector,omitempty" tf:"-"`

	// The zones among which you want to deploy the instance. For more information, see How to use it.
	SelectedZones []*string `json:"selectedZones,omitempty" tf:"selected_zones,omitempty"`

	// The parameters configured for the serverless ApsaraMQ for Kafka instance. See serverless_config below.
	// -> NOTE: If instance_type is set to alikafka_serverless, serverless_config is required.
	ServerlessConfig []ServerlessConfigInitParameters `json:"serverlessConfig,omitempty" tf:"serverless_config,omitempty"`

	// The version of the Instance. Valid values:
	ServiceVersion *string `json:"serviceVersion,omitempty" tf:"service_version,omitempty"`

	// The instance edition. Default value: normal. Valid values:
	SpecType *string `json:"specType,omitempty" tf:"spec_type,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The VPC ID of the instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.VPC
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v1.Reference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v1.Selector `json:"vpcIdSelector,omitempty" tf:"-"`

	// The ID of attaching vswitch to instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// Reference to a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDRef *v1.Reference `json:"vswitchIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDSelector *v1.Selector `json:"vswitchIdSelector,omitempty" tf:"-"`

	// References to Vswitch in vpc to populate vswitchIds.
	// +kubebuilder:validation:Optional
	VswitchIDsRefs []v1.Reference `json:"vswitchIDsRefs,omitempty" tf:"-"`

	// Selector for a list of Vswitch in vpc to populate vswitchIds.
	// +kubebuilder:validation:Optional
	VswitchIDsSelector *v1.Selector `json:"vswitchIDsSelector,omitempty" tf:"-"`

	// The IDs of the vSwitches with which the instance is associated.
	// -> NOTE: If instance_type is set to alikafka or alikafka_serverless, vswitch_ids is required. When instance_type is set to alikafka_confluent, you must specify at least one of the vswitch_id and vswitch_ids, and if you specify both vswitch_id and vswitch_ids, only the vswitch_ids takes effect.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +crossplane:generate:reference:refFieldName=VswitchIDsRefs
	// +crossplane:generate:reference:selectorFieldName=VswitchIDsSelector
	VswitchIds []*string `json:"vswitchIds,omitempty" tf:"vswitch_ids,omitempty"`

	// The zone ID of the instance. The value can be in zone x or region id-x format. NOTE: When the available zone is insufficient, another availability zone may be deployed.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type InstanceObservation struct {

	// The initial configurations of the ApsaraMQ for Kafka instance. The values must be valid JSON strings.
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// The configurations of Confluent. See confluent_config below.
	// -> NOTE: If instance_type is set to alikafka_confluent, confluent_config is required.
	ConfluentConfig []ConfluentConfigObservation `json:"confluentConfig,omitempty" tf:"confluent_config,omitempty"`

	// The number of partitions in a topic that is automatically created.
	DefaultTopicPartitionNum *float64 `json:"defaultTopicPartitionNum,omitempty" tf:"default_topic_partition_num,omitempty"`

	// The deployment type of the instance. NOTE: From version 1.161.0, this attribute supports to be updated. Valid values:
	DeployType *float64 `json:"deployType,omitempty" tf:"deploy_type,omitempty"`

	// The disk size of the instance. When modify this value, it only supports adjust to a greater value.
	// -> NOTE: If instance_type is set to alikafka, disk_size is required.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// The disk type of the instance. Valid values:
	DiskType *float64 `json:"diskType,omitempty" tf:"disk_type,omitempty"`

	// (Available since v1.234.0) The default endpoint of the instance in domain name mode.
	DomainEndpoint *string `json:"domainEndpoint,omitempty" tf:"domain_endpoint,omitempty"`

	// The max bandwidth of the instance. It will be ignored when deploy_type = 5. When modify this value, it only supports adjust to a greater value.
	EIPMax *float64 `json:"eipMax,omitempty" tf:"eip_max,omitempty"`

	// Specify whether to enable the flexible group creation feature. Default value: false. Valid values:
	EnableAutoGroup *bool `json:"enableAutoGroup,omitempty" tf:"enable_auto_group,omitempty"`

	// Specify whether to enable the automatic topic creation feature. Default value: disable. Valid values:
	EnableAutoTopic *string `json:"enableAutoTopic,omitempty" tf:"enable_auto_topic,omitempty"`

	// The EndPoint to access the kafka instance.
	EndPoint *string `json:"endPoint,omitempty" tf:"end_point,omitempty"`

	// (Available since v1.214.1) The number of available groups.
	GroupLeft *float64 `json:"groupLeft,omitempty" tf:"group_left,omitempty"`

	// (Available since v1.214.1) The number of used groups.
	GroupUsed *float64 `json:"groupUsed,omitempty" tf:"group_used,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The type of the Instance. Default value: alikafka. Valid values:
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The max value of io of the instance. When modify this value, it only support adjust to a greater value.
	IoMax *float64 `json:"ioMax,omitempty" tf:"io_max,omitempty"`

	// The traffic specification of the instance. We recommend that you configure this parameter.
	IoMaxSpec *string `json:"ioMaxSpec,omitempty" tf:"io_max_spec,omitempty"`

	// (Available since v1.214.1) The method that you use to purchase partitions.
	IsPartitionBuy *float64 `json:"isPartitionBuy,omitempty" tf:"is_partition_buy,omitempty"`

	// The ID of the key that is used to encrypt data on standard SSDs in the region of the instance. For more information, see How to use it.
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// Name of your Kafka instance. The length should between 3 and 64 characters. If not set, will use instance id as instance name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The billing method of the instance. Default value: PostPaid. Valid values: PostPaid, PrePaid. When modify this value, it only support adjust from PostPaid to PrePaid.
	PaidType *string `json:"paidType,omitempty" tf:"paid_type,omitempty"`

	// (Available since v1.214.1) The number of available partitions.
	PartitionLeft *float64 `json:"partitionLeft,omitempty" tf:"partition_left,omitempty"`

	// The number of partitions.
	PartitionNum *float64 `json:"partitionNum,omitempty" tf:"partition_num,omitempty"`

	// (Available since v1.214.1) The number of used partitions.
	PartitionUsed *float64 `json:"partitionUsed,omitempty" tf:"partition_used,omitempty"`

	// The instance password. NOTE: If instance_type is set to alikafka_confluent, password is required.
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// The ID of the resource group. Note: Once you set a value of this property, you cannot set it to an empty string anymore.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// (Available since v1.234.0) The SSL endpoint of the instance in domain name mode.
	SSLDomainEndpoint *string `json:"sslDomainEndpoint,omitempty" tf:"ssl_domain_endpoint,omitempty"`

	// (Available since v1.234.0) The Secure Sockets Layer (SSL) endpoint of the instance in IP address mode.
	SSLEndpoint *string `json:"sslEndpoint,omitempty" tf:"ssl_endpoint,omitempty"`

	// (Available since v1.234.0) The Simple Authentication and Security Layer (SASL) endpoint of the instance in domain name mode.
	SaslDomainEndpoint *string `json:"saslDomainEndpoint,omitempty" tf:"sasl_domain_endpoint,omitempty"`

	// The ID of security group for this instance. If the security group is empty, system will create a default one.
	SecurityGroup *string `json:"securityGroup,omitempty" tf:"security_group,omitempty"`

	// The zones among which you want to deploy the instance. For more information, see How to use it.
	SelectedZones []*string `json:"selectedZones,omitempty" tf:"selected_zones,omitempty"`

	// The parameters configured for the serverless ApsaraMQ for Kafka instance. See serverless_config below.
	// -> NOTE: If instance_type is set to alikafka_serverless, serverless_config is required.
	ServerlessConfig []ServerlessConfigObservation `json:"serverlessConfig,omitempty" tf:"serverless_config,omitempty"`

	// The version of the Instance. Valid values:
	ServiceVersion *string `json:"serviceVersion,omitempty" tf:"service_version,omitempty"`

	// The instance edition. Default value: normal. Valid values:
	SpecType *string `json:"specType,omitempty" tf:"spec_type,omitempty"`

	// The status of the instance.
	Status *float64 `json:"status,omitempty" tf:"status,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (Available since v1.214.1) The number of available topics.
	TopicLeft *float64 `json:"topicLeft,omitempty" tf:"topic_left,omitempty"`

	// (Available since v1.214.1) The number of purchased topics.
	TopicNumOfBuy *float64 `json:"topicNumOfBuy,omitempty" tf:"topic_num_of_buy,omitempty"`

	// (Available since v1.214.1) The number of used topics.
	TopicUsed *float64 `json:"topicUsed,omitempty" tf:"topic_used,omitempty"`

	// The VPC ID of the instance.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// (Available since v1.283.0) The IP-based endpoint for SASL access over a VPC.
	VPCSaslDomainEndpoint *string `json:"vpcSaslDomainEndpoint,omitempty" tf:"vpc_sasl_domain_endpoint,omitempty"`

	// The ID of attaching vswitch to instance.
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// The IDs of the vSwitches with which the instance is associated.
	// -> NOTE: If instance_type is set to alikafka or alikafka_serverless, vswitch_ids is required. When instance_type is set to alikafka_confluent, you must specify at least one of the vswitch_id and vswitch_ids, and if you specify both vswitch_id and vswitch_ids, only the vswitch_ids takes effect.
	VswitchIds []*string `json:"vswitchIds,omitempty" tf:"vswitch_ids,omitempty"`

	// The zone ID of the instance. The value can be in zone x or region id-x format. NOTE: When the available zone is insufficient, another availability zone may be deployed.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type InstanceParameters struct {

	// The initial configurations of the ApsaraMQ for Kafka instance. The values must be valid JSON strings.
	// +kubebuilder:validation:Optional
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// The configurations of Confluent. See confluent_config below.
	// -> NOTE: If instance_type is set to alikafka_confluent, confluent_config is required.
	// +kubebuilder:validation:Optional
	ConfluentConfig []ConfluentConfigParameters `json:"confluentConfig,omitempty" tf:"confluent_config,omitempty"`

	// The number of partitions in a topic that is automatically created.
	// +kubebuilder:validation:Optional
	DefaultTopicPartitionNum *float64 `json:"defaultTopicPartitionNum,omitempty" tf:"default_topic_partition_num,omitempty"`

	// The deployment type of the instance. NOTE: From version 1.161.0, this attribute supports to be updated. Valid values:
	// +kubebuilder:validation:Optional
	DeployType *float64 `json:"deployType,omitempty" tf:"deploy_type,omitempty"`

	// The disk size of the instance. When modify this value, it only supports adjust to a greater value.
	// -> NOTE: If instance_type is set to alikafka, disk_size is required.
	// +kubebuilder:validation:Optional
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// The disk type of the instance. Valid values:
	// +kubebuilder:validation:Optional
	DiskType *float64 `json:"diskType,omitempty" tf:"disk_type,omitempty"`

	// The max bandwidth of the instance. It will be ignored when deploy_type = 5. When modify this value, it only supports adjust to a greater value.
	// +kubebuilder:validation:Optional
	EIPMax *float64 `json:"eipMax,omitempty" tf:"eip_max,omitempty"`

	// Specify whether to enable the flexible group creation feature. Default value: false. Valid values:
	// +kubebuilder:validation:Optional
	EnableAutoGroup *bool `json:"enableAutoGroup,omitempty" tf:"enable_auto_group,omitempty"`

	// Specify whether to enable the automatic topic creation feature. Default value: disable. Valid values:
	// +kubebuilder:validation:Optional
	EnableAutoTopic *string `json:"enableAutoTopic,omitempty" tf:"enable_auto_topic,omitempty"`

	// The type of the Instance. Default value: alikafka. Valid values:
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// The max value of io of the instance. When modify this value, it only support adjust to a greater value.
	// +kubebuilder:validation:Optional
	IoMax *float64 `json:"ioMax,omitempty" tf:"io_max,omitempty"`

	// The traffic specification of the instance. We recommend that you configure this parameter.
	// +kubebuilder:validation:Optional
	IoMaxSpec *string `json:"ioMaxSpec,omitempty" tf:"io_max_spec,omitempty"`

	// The ID of the key that is used to encrypt data on standard SSDs in the region of the instance. For more information, see How to use it.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/kms/v1alpha1.Key
	// +kubebuilder:validation:Optional
	KMSKeyID *string `json:"kmsKeyId,omitempty" tf:"kms_key_id,omitempty"`

	// Reference to a Key in kms to populate kmsKeyId.
	// +kubebuilder:validation:Optional
	KMSKeyIDRef *v1.Reference `json:"kmsKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in kms to populate kmsKeyId.
	// +kubebuilder:validation:Optional
	KMSKeyIDSelector *v1.Selector `json:"kmsKeyIdSelector,omitempty" tf:"-"`

	// Name of your Kafka instance. The length should between 3 and 64 characters. If not set, will use instance id as instance name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The billing method of the instance. Default value: PostPaid. Valid values: PostPaid, PrePaid. When modify this value, it only support adjust from PostPaid to PrePaid.
	// +kubebuilder:validation:Optional
	PaidType *string `json:"paidType,omitempty" tf:"paid_type,omitempty"`

	// The number of partitions.
	// +kubebuilder:validation:Optional
	PartitionNum *float64 `json:"partitionNum,omitempty" tf:"partition_num,omitempty"`

	// The instance password. NOTE: If instance_type is set to alikafka_confluent, password is required.
	// +kubebuilder:validation:Optional
	Password *string `json:"password,omitempty" tf:"password,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the resource group. Note: Once you set a value of this property, you cannot set it to an empty string anymore.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The ID of security group for this instance. If the security group is empty, system will create a default one.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/ecs/v1alpha1.SecurityGroup
	// +kubebuilder:validation:Optional
	SecurityGroup *string `json:"securityGroup,omitempty" tf:"security_group,omitempty"`

	// Reference to a SecurityGroup in ecs to populate securityGroup.
	// +kubebuilder:validation:Optional
	SecurityGroupRef *v1.Reference `json:"securityGroupRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in ecs to populate securityGroup.
	// +kubebuilder:validation:Optional
	SecurityGroupSelector *v1.Selector `json:"securityGroupSelector,omitempty" tf:"-"`

	// The zones among which you want to deploy the instance. For more information, see How to use it.
	// +kubebuilder:validation:Optional
	SelectedZones []*string `json:"selectedZones,omitempty" tf:"selected_zones,omitempty"`

	// The parameters configured for the serverless ApsaraMQ for Kafka instance. See serverless_config below.
	// -> NOTE: If instance_type is set to alikafka_serverless, serverless_config is required.
	// +kubebuilder:validation:Optional
	ServerlessConfig []ServerlessConfigParameters `json:"serverlessConfig,omitempty" tf:"serverless_config,omitempty"`

	// The version of the Instance. Valid values:
	// +kubebuilder:validation:Optional
	ServiceVersion *string `json:"serviceVersion,omitempty" tf:"service_version,omitempty"`

	// The instance edition. Default value: normal. Valid values:
	// +kubebuilder:validation:Optional
	SpecType *string `json:"specType,omitempty" tf:"spec_type,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The VPC ID of the instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.VPC
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v1.Reference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in vpc to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v1.Selector `json:"vpcIdSelector,omitempty" tf:"-"`

	// The ID of attaching vswitch to instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +kubebuilder:validation:Optional
	VswitchID *string `json:"vswitchId,omitempty" tf:"vswitch_id,omitempty"`

	// Reference to a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDRef *v1.Reference `json:"vswitchIdRef,omitempty" tf:"-"`

	// Selector for a Vswitch in vpc to populate vswitchId.
	// +kubebuilder:validation:Optional
	VswitchIDSelector *v1.Selector `json:"vswitchIdSelector,omitempty" tf:"-"`

	// References to Vswitch in vpc to populate vswitchIds.
	// +kubebuilder:validation:Optional
	VswitchIDsRefs []v1.Reference `json:"vswitchIDsRefs,omitempty" tf:"-"`

	// Selector for a list of Vswitch in vpc to populate vswitchIds.
	// +kubebuilder:validation:Optional
	VswitchIDsSelector *v1.Selector `json:"vswitchIDsSelector,omitempty" tf:"-"`

	// The IDs of the vSwitches with which the instance is associated.
	// -> NOTE: If instance_type is set to alikafka or alikafka_serverless, vswitch_ids is required. When instance_type is set to alikafka_confluent, you must specify at least one of the vswitch_id and vswitch_ids, and if you specify both vswitch_id and vswitch_ids, only the vswitch_ids takes effect.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/vpc/v1alpha1.Vswitch
	// +crossplane:generate:reference:refFieldName=VswitchIDsRefs
	// +crossplane:generate:reference:selectorFieldName=VswitchIDsSelector
	// +kubebuilder:validation:Optional
	VswitchIds []*string `json:"vswitchIds,omitempty" tf:"vswitch_ids,omitempty"`

	// The zone ID of the instance. The value can be in zone x or region id-x format. NOTE: When the available zone is insufficient, another availability zone may be deployed.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ServerlessConfigInitParameters struct {

	// The reserved capacity for publishing messages. The minimum value is 60.
	ReservedPublishCapacity *float64 `json:"reservedPublishCapacity,omitempty" tf:"reserved_publish_capacity,omitempty"`

	// The reserved capacity for subscribing to message. The minimum value is 20.
	ReservedSubscribeCapacity *float64 `json:"reservedSubscribeCapacity,omitempty" tf:"reserved_subscribe_capacity,omitempty"`
}

type ServerlessConfigObservation struct {

	// The reserved capacity for publishing messages. The minimum value is 60.
	ReservedPublishCapacity *float64 `json:"reservedPublishCapacity,omitempty" tf:"reserved_publish_capacity,omitempty"`

	// The reserved capacity for subscribing to message. The minimum value is 20.
	ReservedSubscribeCapacity *float64 `json:"reservedSubscribeCapacity,omitempty" tf:"reserved_subscribe_capacity,omitempty"`
}

type ServerlessConfigParameters struct {

	// The reserved capacity for publishing messages. The minimum value is 60.
	// +kubebuilder:validation:Optional
	ReservedPublishCapacity *float64 `json:"reservedPublishCapacity,omitempty" tf:"reserved_publish_capacity,omitempty"`

	// The reserved capacity for subscribing to message. The minimum value is 20.
	// +kubebuilder:validation:Optional
	ReservedSubscribeCapacity *float64 `json:"reservedSubscribeCapacity,omitempty" tf:"reserved_subscribe_capacity,omitempty"`
}

// InstanceSpec defines the desired state of Instance
type InstanceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceInitParameters `json:"initProvider,omitempty"`
}

// InstanceStatus defines the observed state of Instance.
type InstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Instance is the Schema for the Instances API. Provides a Alicloud AliKafka Instance resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Instance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.deployType) || (has(self.initProvider) && has(self.initProvider.deployType))",message="spec.forProvider.deployType is a required parameter"
	Spec   InstanceSpec   `json:"spec"`
	Status InstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceList contains a list of Instances
type InstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Instance `json:"items"`
}

// Repository type metadata.
var (
	Instance_Kind             = "Instance"
	Instance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Instance_Kind}.String()
	Instance_KindAPIVersion   = Instance_Kind + "." + CRDGroupVersion.String()
	Instance_GroupVersionKind = CRDGroupVersion.WithKind(Instance_Kind)
)

func init() {
	SchemeBuilder.Register(&Instance{}, &InstanceList{})
}
