// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SaslUserInitParameters struct {

	// The instance ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/alikafka/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in alikafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in alikafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// An KMS encrypts password used to a db account. You have to specify one of password and kms_encrypted_password fields.
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a user with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The encryption method. Valid values:
	Mechanism *string `json:"mechanism,omitempty" tf:"mechanism,omitempty"`

	// The password of the SASL user. It may consist of letters, digits, or underlines, with a length of 1 to 64 characters. You have to specify one of password and kms_encrypted_password fields.
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The authentication mechanism. Default value: plain. Valid values:
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The name of the SASL user. The length should between 1 to 64 characters. The characters can only contain a-z, A-Z, 0-9, _ and -.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SaslUserObservation struct {

	// It formats as <instance_id>:<username>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The instance ID.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// An KMS encrypts password used to a db account. You have to specify one of password and kms_encrypted_password fields.
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a user with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The encryption method. Valid values:
	Mechanism *string `json:"mechanism,omitempty" tf:"mechanism,omitempty"`

	// The authentication mechanism. Default value: plain. Valid values:
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The name of the SASL user. The length should between 1 to 64 characters. The characters can only contain a-z, A-Z, 0-9, _ and -.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SaslUserParameters struct {

	// The instance ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/alikafka/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in alikafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in alikafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// An KMS encrypts password used to a db account. You have to specify one of password and kms_encrypted_password fields.
	// +kubebuilder:validation:Optional
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a user with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The encryption method. Valid values:
	// +kubebuilder:validation:Optional
	Mechanism *string `json:"mechanism,omitempty" tf:"mechanism,omitempty"`

	// The password of the SASL user. It may consist of letters, digits, or underlines, with a length of 1 to 64 characters. You have to specify one of password and kms_encrypted_password fields.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The authentication mechanism. Default value: plain. Valid values:
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The name of the SASL user. The length should between 1 to 64 characters. The characters can only contain a-z, A-Z, 0-9, _ and -.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// SaslUserSpec defines the desired state of SaslUser
type SaslUserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SaslUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SaslUserInitParameters `json:"initProvider,omitempty"`
}

// SaslUserStatus defines the observed state of SaslUser.
type SaslUserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SaslUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SaslUser is the Schema for the SaslUsers API. Provides a Alicloud AliKafka Sasl User resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type SaslUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   SaslUserSpec   `json:"spec"`
	Status SaslUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SaslUserList contains a list of SaslUsers
type SaslUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SaslUser `json:"items"`
}

// Repository type metadata.
var (
	SaslUser_Kind             = "SaslUser"
	SaslUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SaslUser_Kind}.String()
	SaslUser_KindAPIVersion   = SaslUser_Kind + "." + CRDGroupVersion.String()
	SaslUser_GroupVersionKind = CRDGroupVersion.WithKind(SaslUser_Kind)
)

func init() {
	SchemeBuilder.Register(&SaslUser{}, &SaslUserList{})
}
