apiVersion: oss.alibabacloud.m.crossplane.io/v1alpha1
kind: BucketRequestPayment
metadata:
  namespace: default
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketrequestpayment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: CreateBucket
    payer: Requester

---

apiVersion: oss.alibabacloud.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  namespace: default
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketrequestpayment
  labels:
    testing.upbound.io/example-name: CreateBucket
  name: createbucket
spec:
  forProvider:
    bucket: crossplane-example-202504081600
    storageClass: Standard
