// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DefaultPatchBaselineInitParameters struct {

	// The name of the patch baseline.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/oos/v1alpha1.PatchBaseline
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	PatchBaselineName *string `json:"patchBaselineName,omitempty" tf:"patch_baseline_name,omitempty"`

	// Reference to a PatchBaseline in oos to populate patchBaselineName.
	// +kubebuilder:validation:Optional
	PatchBaselineNameRef *v1.Reference `json:"patchBaselineNameRef,omitempty" tf:"-"`

	// Selector for a PatchBaseline in oos to populate patchBaselineName.
	// +kubebuilder:validation:Optional
	PatchBaselineNameSelector *v1.Selector `json:"patchBaselineNameSelector,omitempty" tf:"-"`
}

type DefaultPatchBaselineObservation struct {

	// The key of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the patch baseline.
	PatchBaselineID *string `json:"patchBaselineId,omitempty" tf:"patch_baseline_id,omitempty"`

	// The name of the patch baseline.
	PatchBaselineName *string `json:"patchBaselineName,omitempty" tf:"patch_baseline_name,omitempty"`
}

type DefaultPatchBaselineParameters struct {

	// The name of the patch baseline.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/oos/v1alpha1.PatchBaseline
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	PatchBaselineName *string `json:"patchBaselineName,omitempty" tf:"patch_baseline_name,omitempty"`

	// Reference to a PatchBaseline in oos to populate patchBaselineName.
	// +kubebuilder:validation:Optional
	PatchBaselineNameRef *v1.Reference `json:"patchBaselineNameRef,omitempty" tf:"-"`

	// Selector for a PatchBaseline in oos to populate patchBaselineName.
	// +kubebuilder:validation:Optional
	PatchBaselineNameSelector *v1.Selector `json:"patchBaselineNameSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// DefaultPatchBaselineSpec defines the desired state of DefaultPatchBaseline
type DefaultPatchBaselineSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DefaultPatchBaselineParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DefaultPatchBaselineInitParameters `json:"initProvider,omitempty"`
}

// DefaultPatchBaselineStatus defines the observed state of DefaultPatchBaseline.
type DefaultPatchBaselineStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DefaultPatchBaselineObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DefaultPatchBaseline is the Schema for the DefaultPatchBaselines API. Provides a Alicloud Oos Default Patch Baseline resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type DefaultPatchBaseline struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DefaultPatchBaselineSpec   `json:"spec"`
	Status            DefaultPatchBaselineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DefaultPatchBaselineList contains a list of DefaultPatchBaselines
type DefaultPatchBaselineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DefaultPatchBaseline `json:"items"`
}

// Repository type metadata.
var (
	DefaultPatchBaseline_Kind             = "DefaultPatchBaseline"
	DefaultPatchBaseline_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DefaultPatchBaseline_Kind}.String()
	DefaultPatchBaseline_KindAPIVersion   = DefaultPatchBaseline_Kind + "." + CRDGroupVersion.String()
	DefaultPatchBaseline_GroupVersionKind = CRDGroupVersion.WithKind(DefaultPatchBaseline_Kind)
)

func init() {
	SchemeBuilder.Register(&DefaultPatchBaseline{}, &DefaultPatchBaselineList{})
}
