// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ParameterInitParameters struct {

	// The constraints of the common parameter. This value follows the json format. By default, this parameter is null. Valid values:
	Constraints *string `json:"constraints,omitempty" tf:"constraints,omitempty"`

	// The description of the common parameter. The description must be 1 to 200 characters in length.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the common parameter. The name must be 2 to 180 characters in length, and can contain letters, digits, hyphens (-), forward slashes (/) and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, ALICLOUD, or OOS.
	ParameterName *string `json:"parameterName,omitempty" tf:"parameter_name,omitempty"`

	// The ID of the Resource Group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The data type of the common parameter. Valid values: String and StringList.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value of the common parameter. The value must be 1 to 4096 characters in length.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParameterObservation struct {

	// The constraints of the common parameter. This value follows the json format. By default, this parameter is null. Valid values:
	Constraints *string `json:"constraints,omitempty" tf:"constraints,omitempty"`

	// The description of the common parameter. The description must be 1 to 200 characters in length.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Its value is same as parameter_name.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the common parameter. The name must be 2 to 180 characters in length, and can contain letters, digits, hyphens (-), forward slashes (/) and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, ALICLOUD, or OOS.
	ParameterName *string `json:"parameterName,omitempty" tf:"parameter_name,omitempty"`

	// The ID of the Resource Group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The data type of the common parameter. Valid values: String and StringList.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value of the common parameter. The value must be 1 to 4096 characters in length.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParameterParameters struct {

	// The constraints of the common parameter. This value follows the json format. By default, this parameter is null. Valid values:
	// +kubebuilder:validation:Optional
	Constraints *string `json:"constraints,omitempty" tf:"constraints,omitempty"`

	// The description of the common parameter. The description must be 1 to 200 characters in length.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the common parameter. The name must be 2 to 180 characters in length, and can contain letters, digits, hyphens (-), forward slashes (/) and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, ALICLOUD, or OOS.
	// +kubebuilder:validation:Optional
	ParameterName *string `json:"parameterName,omitempty" tf:"parameter_name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the Resource Group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The data type of the common parameter. Valid values: String and StringList.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value of the common parameter. The value must be 1 to 4096 characters in length.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// ParameterSpec defines the desired state of Parameter
type ParameterSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ParameterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ParameterInitParameters `json:"initProvider,omitempty"`
}

// ParameterStatus defines the observed state of Parameter.
type ParameterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ParameterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Parameter is the Schema for the Parameters API. Provides a Alicloud OOS Parameter resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Parameter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parameterName) || (has(self.initProvider) && has(self.initProvider.parameterName))",message="spec.forProvider.parameterName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   ParameterSpec   `json:"spec"`
	Status ParameterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ParameterList contains a list of Parameters
type ParameterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Parameter `json:"items"`
}

// Repository type metadata.
var (
	Parameter_Kind             = "Parameter"
	Parameter_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Parameter_Kind}.String()
	Parameter_KindAPIVersion   = Parameter_Kind + "." + CRDGroupVersion.String()
	Parameter_GroupVersionKind = CRDGroupVersion.WithKind(Parameter_Kind)
)

func init() {
	SchemeBuilder.Register(&Parameter{}, &ParameterList{})
}
