// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type StateConfigurationInitParameters struct {

	// Configuration mode. Valid values: ApplyAndAutoCorrect, ApplyAndMonitor, ApplyOnly.
	ConfigureMode *string `json:"configureMode,omitempty" tf:"configure_mode,omitempty"`

	// The description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The parameter of the Template. This field is in the format of JSON strings. For detailed definition instructions, please refer to Metadata types that are supported by a configuration list.
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Timing expression.
	ScheduleExpression *string `json:"scheduleExpression,omitempty" tf:"schedule_expression,omitempty"`

	// Timing type. Valid values: rate.
	ScheduleType *string `json:"scheduleType,omitempty" tf:"schedule_type,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The Target resources.  This field is in the format of JSON strings. For detailed definition instructions, please refer to Parameter.
	Targets *string `json:"targets,omitempty" tf:"targets,omitempty"`

	// The name of the template.
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The version number. If you do not specify this parameter, the system uses the latest version.
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`
}

type StateConfigurationObservation struct {

	// Configuration mode. Valid values: ApplyAndAutoCorrect, ApplyAndMonitor, ApplyOnly.
	ConfigureMode *string `json:"configureMode,omitempty" tf:"configure_mode,omitempty"`

	// The description of the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The value is formate as <state_configuration_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The parameter of the Template. This field is in the format of JSON strings. For detailed definition instructions, please refer to Metadata types that are supported by a configuration list.
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The ID of the resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Timing expression.
	ScheduleExpression *string `json:"scheduleExpression,omitempty" tf:"schedule_expression,omitempty"`

	// Timing type. Valid values: rate.
	ScheduleType *string `json:"scheduleType,omitempty" tf:"schedule_type,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The Target resources.  This field is in the format of JSON strings. For detailed definition instructions, please refer to Parameter.
	Targets *string `json:"targets,omitempty" tf:"targets,omitempty"`

	// The name of the template.
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The version number. If you do not specify this parameter, the system uses the latest version.
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`
}

type StateConfigurationParameters struct {

	// Configuration mode. Valid values: ApplyAndAutoCorrect, ApplyAndMonitor, ApplyOnly.
	// +kubebuilder:validation:Optional
	ConfigureMode *string `json:"configureMode,omitempty" tf:"configure_mode,omitempty"`

	// The description of the resource.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The parameter of the Template. This field is in the format of JSON strings. For detailed definition instructions, please refer to Metadata types that are supported by a configuration list.
	// +kubebuilder:validation:Optional
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Timing expression.
	// +kubebuilder:validation:Optional
	ScheduleExpression *string `json:"scheduleExpression,omitempty" tf:"schedule_expression,omitempty"`

	// Timing type. Valid values: rate.
	// +kubebuilder:validation:Optional
	ScheduleType *string `json:"scheduleType,omitempty" tf:"schedule_type,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The Target resources.  This field is in the format of JSON strings. For detailed definition instructions, please refer to Parameter.
	// +kubebuilder:validation:Optional
	Targets *string `json:"targets,omitempty" tf:"targets,omitempty"`

	// The name of the template.
	// +kubebuilder:validation:Optional
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The version number. If you do not specify this parameter, the system uses the latest version.
	// +kubebuilder:validation:Optional
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`
}

// StateConfigurationSpec defines the desired state of StateConfiguration
type StateConfigurationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     StateConfigurationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StateConfigurationInitParameters `json:"initProvider,omitempty"`
}

// StateConfigurationStatus defines the observed state of StateConfiguration.
type StateConfigurationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StateConfigurationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StateConfiguration is the Schema for the StateConfigurations API. Provides a Alicloud OOS State Configuration resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type StateConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scheduleExpression) || (has(self.initProvider) && has(self.initProvider.scheduleExpression))",message="spec.forProvider.scheduleExpression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scheduleType) || (has(self.initProvider) && has(self.initProvider.scheduleType))",message="spec.forProvider.scheduleType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targets) || (has(self.initProvider) && has(self.initProvider.targets))",message="spec.forProvider.targets is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateName) || (has(self.initProvider) && has(self.initProvider.templateName))",message="spec.forProvider.templateName is a required parameter"
	Spec   StateConfigurationSpec   `json:"spec"`
	Status StateConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StateConfigurationList contains a list of StateConfigurations
type StateConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StateConfiguration `json:"items"`
}

// Repository type metadata.
var (
	StateConfiguration_Kind             = "StateConfiguration"
	StateConfiguration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StateConfiguration_Kind}.String()
	StateConfiguration_KindAPIVersion   = StateConfiguration_Kind + "." + CRDGroupVersion.String()
	StateConfiguration_GroupVersionKind = CRDGroupVersion.WithKind(StateConfiguration_Kind)
)

func init() {
	SchemeBuilder.Register(&StateConfiguration{}, &StateConfigurationList{})
}
