apiVersion: oos.alibabacloud.crossplane.io/v1alpha1
kind: SecretParameter
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/secretparameter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: terraform-example
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: cn-beijing
    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.example.groups.0.id}
    secretParameterName: terraform-example
    tags:
      Created: TF
      For: OosSecretParameter
    type: Secret
    valueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: kms.alibabacloud.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/secretparameter
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: terraform-example
    pendingWindowInDays: 7
    region: cn-beijing
    status: Enabled
