apiVersion: alikafka.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    config: |-
      ${jsonencode(
          {
            "kafka.log.retention.hours" : "96",
            "kafka.message.max.bytes" : "1048576"
          }
        )}
    deployType: 5
    diskSize: 500
    diskType: 1
    ioMax: 20
    name: ${var.instance_name}-${random_integer.default.result}
    partitionNum: 50
    region: cn-beijing
    securityGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    specType: professional
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/12
    region: cn-beijing

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    zoneId: ${data.alicloud_zones.default.zones[0].id}
