apiVersion: alikafka.alibabacloud.crossplane.io/v1alpha1
kind: ScheduledScalingRule
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/scheduledscalingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    durationMinutes: "100"
    enable: false
    firstScheduledTime: "1769578000000"
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: cn-beijing
    repeatType: Weekly
    reservedPubFlow: "200"
    reservedSubFlow: "200"
    ruleName: ${var.name}
    scheduleType: repeat
    timeZone: GMT+8
    weeklyTypes:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

---

apiVersion: alikafka.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/scheduledscalingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    config: '{"enable.acl":"true"}'
    deployType: "4"
    instanceType: alikafka_serverless
    region: cn-beijing
    securityGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    serverlessConfig:
    - reservedPublishCapacity: 60
      reservedSubscribeCapacity: 60
    serviceVersion: 3.3.1
    specType: normal
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/scheduledscalingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/scheduledscalingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: alikafka/v1alpha1/scheduledscalingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 10.4.0.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.default.zones.0.id}
