// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ScanRuleInitParameters struct {

	// Instance ID
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Set of namespaces:
	Namespaces []*string `json:"namespaces,omitempty" tf:"namespaces,omitempty"`

	// Repository list:
	RepoNames []*string `json:"repoNames,omitempty" tf:"repo_names,omitempty"`

	// Regular expression for matching tags that trigger a scan
	RepoTagFilterPattern *string `json:"repoTagFilterPattern,omitempty" tf:"repo_tag_filter_pattern,omitempty"`

	// Event rule name
	RuleName *string `json:"ruleName,omitempty" tf:"rule_name,omitempty"`

	// Scan scope
	ScanScope *string `json:"scanScope,omitempty" tf:"scan_scope,omitempty"`

	// Scan type:
	ScanType *string `json:"scanType,omitempty" tf:"scan_type,omitempty"`

	// Trigger type
	TriggerType *string `json:"triggerType,omitempty" tf:"trigger_type,omitempty"`
}

type ScanRuleObservation struct {

	// Creation time
	CreateTime *float64 `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The ID of the resource supplied above.The value is formulated as <instance_id>:<scan_rule_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Instance ID
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Set of namespaces:
	Namespaces []*string `json:"namespaces,omitempty" tf:"namespaces,omitempty"`

	// Repository list:
	RepoNames []*string `json:"repoNames,omitempty" tf:"repo_names,omitempty"`

	// Regular expression for matching tags that trigger a scan
	RepoTagFilterPattern *string `json:"repoTagFilterPattern,omitempty" tf:"repo_tag_filter_pattern,omitempty"`

	// Event rule name
	RuleName *string `json:"ruleName,omitempty" tf:"rule_name,omitempty"`

	// Rule ID
	ScanRuleID *string `json:"scanRuleId,omitempty" tf:"scan_rule_id,omitempty"`

	// Scan scope
	ScanScope *string `json:"scanScope,omitempty" tf:"scan_scope,omitempty"`

	// Scan type:
	ScanType *string `json:"scanType,omitempty" tf:"scan_type,omitempty"`

	// Trigger type
	TriggerType *string `json:"triggerType,omitempty" tf:"trigger_type,omitempty"`
}

type ScanRuleParameters struct {

	// Instance ID
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Set of namespaces:
	// +kubebuilder:validation:Optional
	Namespaces []*string `json:"namespaces,omitempty" tf:"namespaces,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// Repository list:
	// +kubebuilder:validation:Optional
	RepoNames []*string `json:"repoNames,omitempty" tf:"repo_names,omitempty"`

	// Regular expression for matching tags that trigger a scan
	// +kubebuilder:validation:Optional
	RepoTagFilterPattern *string `json:"repoTagFilterPattern,omitempty" tf:"repo_tag_filter_pattern,omitempty"`

	// Event rule name
	// +kubebuilder:validation:Optional
	RuleName *string `json:"ruleName,omitempty" tf:"rule_name,omitempty"`

	// Scan scope
	// +kubebuilder:validation:Optional
	ScanScope *string `json:"scanScope,omitempty" tf:"scan_scope,omitempty"`

	// Scan type:
	// +kubebuilder:validation:Optional
	ScanType *string `json:"scanType,omitempty" tf:"scan_type,omitempty"`

	// Trigger type
	// +kubebuilder:validation:Optional
	TriggerType *string `json:"triggerType,omitempty" tf:"trigger_type,omitempty"`
}

// ScanRuleSpec defines the desired state of ScanRule
type ScanRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScanRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScanRuleInitParameters `json:"initProvider,omitempty"`
}

// ScanRuleStatus defines the observed state of ScanRule.
type ScanRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScanRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScanRule is the Schema for the ScanRules API. Provides a Alicloud CR Scan Rule resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type ScanRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repoTagFilterPattern) || (has(self.initProvider) && has(self.initProvider.repoTagFilterPattern))",message="spec.forProvider.repoTagFilterPattern is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ruleName) || (has(self.initProvider) && has(self.initProvider.ruleName))",message="spec.forProvider.ruleName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scanScope) || (has(self.initProvider) && has(self.initProvider.scanScope))",message="spec.forProvider.scanScope is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scanType) || (has(self.initProvider) && has(self.initProvider.scanType))",message="spec.forProvider.scanType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.triggerType) || (has(self.initProvider) && has(self.initProvider.triggerType))",message="spec.forProvider.triggerType is a required parameter"
	Spec   ScanRuleSpec   `json:"spec"`
	Status ScanRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScanRuleList contains a list of ScanRules
type ScanRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScanRule `json:"items"`
}

// Repository type metadata.
var (
	ScanRule_Kind             = "ScanRule"
	ScanRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScanRule_Kind}.String()
	ScanRule_KindAPIVersion   = ScanRule_Kind + "." + CRDGroupVersion.String()
	ScanRule_GroupVersionKind = CRDGroupVersion.WithKind(ScanRule_Kind)
)

func init() {
	SchemeBuilder.Register(&ScanRule{}, &ScanRuleList{})
}
