// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/ack/v1alpha1"
	v1alpha1ackone "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/ackone/v1alpha1"
	v1alpha1alb "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/alb/v1alpha1"
	v1alpha1alidns "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/alidns/v1alpha1"
	v1alpha1alikafka "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/alikafka/v1alpha1"
	v1alpha1cdn "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cdn/v1alpha1"
	v1alpha1cloudmonitorservice "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cloudmonitorservice/v1alpha1"
	v1alpha1cr "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1"
	v1alpha1ecs "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/ecs/v1alpha1"
	v1alpha1fcv3 "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/fcv3/v1alpha1"
	v1alpha1kms "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/kms/v1alpha1"
	v1alpha1messageservice "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/messageservice/v1alpha1"
	v1alpha1oos "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/oos/v1alpha1"
	v1alpha1oss "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/oss/v1alpha1"
	v1alpha1polardb "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/polardb/v1alpha1"
	v1alpha1privatelink "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/privatelink/v1alpha1"
	v1alpha1quotas "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/quotas/v1alpha1"
	v1alpha1ram "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/ram/v1alpha1"
	v1alpha1slb "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/slb/v1alpha1"
	v1alpha1tair "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/tair/v1alpha1"
	v1alpha1namespaced "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/v1beta1"
	v1alpha1vpc "github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/vpc/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1ackone.SchemeBuilder.AddToScheme,
		v1alpha1alb.SchemeBuilder.AddToScheme,
		v1alpha1alidns.SchemeBuilder.AddToScheme,
		v1alpha1alikafka.SchemeBuilder.AddToScheme,
		v1alpha1cdn.SchemeBuilder.AddToScheme,
		v1alpha1cloudmonitorservice.SchemeBuilder.AddToScheme,
		v1alpha1cr.SchemeBuilder.AddToScheme,
		v1alpha1ecs.SchemeBuilder.AddToScheme,
		v1alpha1fcv3.SchemeBuilder.AddToScheme,
		v1alpha1kms.SchemeBuilder.AddToScheme,
		v1alpha1messageservice.SchemeBuilder.AddToScheme,
		v1alpha1oos.SchemeBuilder.AddToScheme,
		v1alpha1oss.SchemeBuilder.AddToScheme,
		v1alpha1polardb.SchemeBuilder.AddToScheme,
		v1alpha1privatelink.SchemeBuilder.AddToScheme,
		v1alpha1quotas.SchemeBuilder.AddToScheme,
		v1alpha1ram.SchemeBuilder.AddToScheme,
		v1alpha1slb.SchemeBuilder.AddToScheme,
		v1alpha1tair.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1vpc.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
