---
apiVersion: cr.alibabacloud.crossplane.io/v1alpha1
kind: EeInstance
metadata:
  annotations:
    meta.crossplane.io/example-id: cr-v1alpha1-test-ee-instance-1
  labels:
    testing.crossplane.io/example-name: test-ee-instance-1
  name: test-ee-instance-1
spec:
  forProvider:
    region: us-west-1
    instanceName: cr-ee-test-inst-1
    instanceType: Advanced
    paymentType: Subscription
    period: 1
    renewPeriod: 1
    renewalStatus: AutoRenewal
