apiVersion: messageservice.alibabacloud.m.crossplane.io/v1alpha1
kind: Endpoint
metadata:
  namespace: default
  annotations:
    meta.upbound.io/example-id: messageservice/v1alpha1/endpoint
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    endpointEnabled: true
    endpointType: public
