// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ExecutionInitParameters struct {

	// The description of OOS Execution.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The loop mode of OOS Execution.
	LoopMode *string `json:"loopMode,omitempty" tf:"loop_mode,omitempty"`

	// The mode of OOS Execution. Valid: Automatic, Debug. Default to Automatic.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The parameters required by the template. Default to {}.
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The id of parent execution.
	ParentExecutionID *string `json:"parentExecutionId,omitempty" tf:"parent_execution_id,omitempty"`

	// The mode of safety check.
	SafetyCheck *string `json:"safetyCheck,omitempty" tf:"safety_check,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The content of template. When the user selects an existing template to create and execute a task, it is not necessary to pass in this field.
	TemplateContent *string `json:"templateContent,omitempty" tf:"template_content,omitempty"`

	// The name of execution template.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/oos/v1alpha1.Template
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("template_name",false)
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// Reference to a Template in oos to populate templateName.
	// +kubebuilder:validation:Optional
	TemplateNameRef *v1.Reference `json:"templateNameRef,omitempty" tf:"-"`

	// Selector for a Template in oos to populate templateName.
	// +kubebuilder:validation:Optional
	TemplateNameSelector *v1.Selector `json:"templateNameSelector,omitempty" tf:"-"`

	// The version of execution template.
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`
}

type ExecutionObservation struct {

	// The counters of OOS Execution.
	Counters *string `json:"counters,omitempty" tf:"counters,omitempty"`

	// The time when the execution was created.
	CreateDate *string `json:"createDate,omitempty" tf:"create_date,omitempty"`

	// The description of OOS Execution.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The time when the execution was ended.
	EndDate *string `json:"endDate,omitempty" tf:"end_date,omitempty"`

	// The user who execute the template.
	ExecutedBy *string `json:"executedBy,omitempty" tf:"executed_by,omitempty"`

	// The id of OOS Execution.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether to include subtasks.
	IsParent *bool `json:"isParent,omitempty" tf:"is_parent,omitempty"`

	// The loop mode of OOS Execution.
	LoopMode *string `json:"loopMode,omitempty" tf:"loop_mode,omitempty"`

	// The mode of OOS Execution. Valid: Automatic, Debug. Default to Automatic.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The outputs of OOS Execution.
	Outputs *string `json:"outputs,omitempty" tf:"outputs,omitempty"`

	// The parameters required by the template. Default to {}.
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The id of parent execution.
	ParentExecutionID *string `json:"parentExecutionId,omitempty" tf:"parent_execution_id,omitempty"`

	// The role that executes the current template.
	RAMRole *string `json:"ramRole,omitempty" tf:"ram_role,omitempty"`

	// The mode of safety check.
	SafetyCheck *string `json:"safetyCheck,omitempty" tf:"safety_check,omitempty"`

	// The time when the execution was started.
	StartDate *string `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// The status of OOS Execution.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The message of status.
	StatusMessage *string `json:"statusMessage,omitempty" tf:"status_message,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The content of template. When the user selects an existing template to create and execute a task, it is not necessary to pass in this field.
	TemplateContent *string `json:"templateContent,omitempty" tf:"template_content,omitempty"`

	// The id of template.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// The name of execution template.
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The version of execution template.
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`

	// The time when the execution was updated.
	UpdateDate *string `json:"updateDate,omitempty" tf:"update_date,omitempty"`
}

type ExecutionParameters struct {

	// The description of OOS Execution.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The loop mode of OOS Execution.
	// +kubebuilder:validation:Optional
	LoopMode *string `json:"loopMode,omitempty" tf:"loop_mode,omitempty"`

	// The mode of OOS Execution. Valid: Automatic, Debug. Default to Automatic.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The parameters required by the template. Default to {}.
	// +kubebuilder:validation:Optional
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The id of parent execution.
	// +kubebuilder:validation:Optional
	ParentExecutionID *string `json:"parentExecutionId,omitempty" tf:"parent_execution_id,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The mode of safety check.
	// +kubebuilder:validation:Optional
	SafetyCheck *string `json:"safetyCheck,omitempty" tf:"safety_check,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The content of template. When the user selects an existing template to create and execute a task, it is not necessary to pass in this field.
	// +kubebuilder:validation:Optional
	TemplateContent *string `json:"templateContent,omitempty" tf:"template_content,omitempty"`

	// The name of execution template.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/oos/v1alpha1.Template
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("template_name",false)
	// +kubebuilder:validation:Optional
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// Reference to a Template in oos to populate templateName.
	// +kubebuilder:validation:Optional
	TemplateNameRef *v1.Reference `json:"templateNameRef,omitempty" tf:"-"`

	// Selector for a Template in oos to populate templateName.
	// +kubebuilder:validation:Optional
	TemplateNameSelector *v1.Selector `json:"templateNameSelector,omitempty" tf:"-"`

	// The version of execution template.
	// +kubebuilder:validation:Optional
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`
}

// ExecutionSpec defines the desired state of Execution
type ExecutionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ExecutionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExecutionInitParameters `json:"initProvider,omitempty"`
}

// ExecutionStatus defines the observed state of Execution.
type ExecutionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExecutionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Execution is the Schema for the Executions API. Provides a OOS Execution resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type Execution struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ExecutionSpec   `json:"spec"`
	Status            ExecutionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExecutionList contains a list of Executions
type ExecutionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Execution `json:"items"`
}

// Repository type metadata.
var (
	Execution_Kind             = "Execution"
	Execution_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Execution_Kind}.String()
	Execution_KindAPIVersion   = Execution_Kind + "." + CRDGroupVersion.String()
	Execution_GroupVersionKind = CRDGroupVersion.WithKind(Execution_Kind)
)

func init() {
	SchemeBuilder.Register(&Execution{}, &ExecutionList{})
}
