// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-alibabacloud/apis/kms/v1alpha1"
	v1alpha11 "github.com/crossplane-contrib/provider-alibabacloud/apis/oss/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ApplicationGroup.
func (mg *ApplicationGroup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ApplicationName),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ApplicationNameRef,
		Selector:     mg.Spec.ForProvider.ApplicationNameSelector,
		To: reference.To{
			List:    &ApplicationList{},
			Managed: &Application{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ApplicationName")
	}
	mg.Spec.ForProvider.ApplicationName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ApplicationNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ApplicationName),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ApplicationNameRef,
		Selector:     mg.Spec.InitProvider.ApplicationNameSelector,
		To: reference.To{
			List:    &ApplicationList{},
			Managed: &Application{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ApplicationName")
	}
	mg.Spec.InitProvider.ApplicationName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ApplicationNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this DefaultPatchBaseline.
func (mg *DefaultPatchBaseline) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PatchBaselineName),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PatchBaselineNameRef,
		Selector:     mg.Spec.ForProvider.PatchBaselineNameSelector,
		To: reference.To{
			List:    &PatchBaselineList{},
			Managed: &PatchBaseline{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PatchBaselineName")
	}
	mg.Spec.ForProvider.PatchBaselineName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PatchBaselineNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PatchBaselineName),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PatchBaselineNameRef,
		Selector:     mg.Spec.InitProvider.PatchBaselineNameSelector,
		To: reference.To{
			List:    &PatchBaselineList{},
			Managed: &PatchBaseline{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PatchBaselineName")
	}
	mg.Spec.InitProvider.PatchBaselineName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PatchBaselineNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Execution.
func (mg *Execution) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TemplateName),
		Extract:      resource.ExtractParamPath("template_name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TemplateNameRef,
		Selector:     mg.Spec.ForProvider.TemplateNameSelector,
		To: reference.To{
			List:    &TemplateList{},
			Managed: &Template{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TemplateName")
	}
	mg.Spec.ForProvider.TemplateName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TemplateNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TemplateName),
		Extract:      resource.ExtractParamPath("template_name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TemplateNameRef,
		Selector:     mg.Spec.InitProvider.TemplateNameSelector,
		To: reference.To{
			List:    &TemplateList{},
			Managed: &Template{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TemplateName")
	}
	mg.Spec.InitProvider.TemplateName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TemplateNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SecretParameter.
func (mg *SecretParameter) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KeyID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KeyIDRef,
		Selector:     mg.Spec.ForProvider.KeyIDSelector,
		To: reference.To{
			List:    &v1alpha1.KeyList{},
			Managed: &v1alpha1.Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KeyID")
	}
	mg.Spec.ForProvider.KeyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KeyIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KeyID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.KeyIDRef,
		Selector:     mg.Spec.InitProvider.KeyIDSelector,
		To: reference.To{
			List:    &v1alpha1.KeyList{},
			Managed: &v1alpha1.Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KeyID")
	}
	mg.Spec.InitProvider.KeyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KeyIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ServiceSetting.
func (mg *ServiceSetting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DeliveryOssBucketName),
		Extract:      resource.ExtractParamPath("bucket", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DeliveryOssBucketNameRef,
		Selector:     mg.Spec.ForProvider.DeliveryOssBucketNameSelector,
		To: reference.To{
			List:    &v1alpha11.BucketList{},
			Managed: &v1alpha11.Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DeliveryOssBucketName")
	}
	mg.Spec.ForProvider.DeliveryOssBucketName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DeliveryOssBucketNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DeliveryOssBucketName),
		Extract:      resource.ExtractParamPath("bucket", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DeliveryOssBucketNameRef,
		Selector:     mg.Spec.InitProvider.DeliveryOssBucketNameSelector,
		To: reference.To{
			List:    &v1alpha11.BucketList{},
			Managed: &v1alpha11.Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DeliveryOssBucketName")
	}
	mg.Spec.InitProvider.DeliveryOssBucketName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DeliveryOssBucketNameRef = rsp.ResolvedReference

	return nil
}
