// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SecretParameterInitParameters struct {

	// The constraints of the encryption parameter. By default, this parameter is null. Valid values:
	Constraints *string `json:"constraints,omitempty" tf:"constraints,omitempty"`

	// The description of the encryption parameter. The description must be 1 to 200 characters in length.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the KMS instance.
	DkmsInstanceID *string `json:"dkmsInstanceId,omitempty" tf:"dkms_instance_id,omitempty"`

	// The Customer Master Key (CMK) of Key Management Service (KMS) that is used to encrypt the parameter.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/kms/v1alpha1.Key
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// Reference to a Key in kms to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDRef *v1.Reference `json:"keyIdRef,omitempty" tf:"-"`

	// Selector for a Key in kms to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDSelector *v1.Selector `json:"keyIdSelector,omitempty" tf:"-"`

	// The ID of the Resource Group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The name of the encryption parameter.  The name must be 2 to 180 characters in length, and can contain letters, digits, hyphens (-), forward slashes (/) and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, ALICLOUD, or OOS.
	SecretParameterName *string `json:"secretParameterName,omitempty" tf:"secret_parameter_name,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The data type of the encryption parameter. Valid values: Secret.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value of the encryption parameter. The value must be 1 to 4096 characters in length.
	ValueSecretRef v1.SecretKeySelector `json:"valueSecretRef" tf:"-"`
}

type SecretParameterObservation struct {

	// The constraints of the encryption parameter. By default, this parameter is null. Valid values:
	Constraints *string `json:"constraints,omitempty" tf:"constraints,omitempty"`

	// Parameter creation time
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The description of the encryption parameter. The description must be 1 to 200 characters in length.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the KMS instance.
	DkmsInstanceID *string `json:"dkmsInstanceId,omitempty" tf:"dkms_instance_id,omitempty"`

	// The ID of the resource supplied above.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The Customer Master Key (CMK) of Key Management Service (KMS) that is used to encrypt the parameter.
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// The ID of the Resource Group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The name of the encryption parameter.  The name must be 2 to 180 characters in length, and can contain letters, digits, hyphens (-), forward slashes (/) and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, ALICLOUD, or OOS.
	SecretParameterName *string `json:"secretParameterName,omitempty" tf:"secret_parameter_name,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The data type of the encryption parameter. Valid values: Secret.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SecretParameterParameters struct {

	// The constraints of the encryption parameter. By default, this parameter is null. Valid values:
	// +kubebuilder:validation:Optional
	Constraints *string `json:"constraints,omitempty" tf:"constraints,omitempty"`

	// The description of the encryption parameter. The description must be 1 to 200 characters in length.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the KMS instance.
	// +kubebuilder:validation:Optional
	DkmsInstanceID *string `json:"dkmsInstanceId,omitempty" tf:"dkms_instance_id,omitempty"`

	// The Customer Master Key (CMK) of Key Management Service (KMS) that is used to encrypt the parameter.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/kms/v1alpha1.Key
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// Reference to a Key in kms to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDRef *v1.Reference `json:"keyIdRef,omitempty" tf:"-"`

	// Selector for a Key in kms to populate keyId.
	// +kubebuilder:validation:Optional
	KeyIDSelector *v1.Selector `json:"keyIdSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the Resource Group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The name of the encryption parameter.  The name must be 2 to 180 characters in length, and can contain letters, digits, hyphens (-), forward slashes (/) and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, ALICLOUD, or OOS.
	// +kubebuilder:validation:Optional
	SecretParameterName *string `json:"secretParameterName,omitempty" tf:"secret_parameter_name,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The data type of the encryption parameter. Valid values: Secret.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value of the encryption parameter. The value must be 1 to 4096 characters in length.
	// +kubebuilder:validation:Optional
	ValueSecretRef v1.SecretKeySelector `json:"valueSecretRef" tf:"-"`
}

// SecretParameterSpec defines the desired state of SecretParameter
type SecretParameterSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SecretParameterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecretParameterInitParameters `json:"initProvider,omitempty"`
}

// SecretParameterStatus defines the observed state of SecretParameter.
type SecretParameterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecretParameterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecretParameter is the Schema for the SecretParameters API. Provides a Alicloud Operation Orchestration Service (OOS) Secret Parameter resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type SecretParameter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretParameterName) || (has(self.initProvider) && has(self.initProvider.secretParameterName))",message="spec.forProvider.secretParameterName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueSecretRef)",message="spec.forProvider.valueSecretRef is a required parameter"
	Spec   SecretParameterSpec   `json:"spec"`
	Status SecretParameterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecretParameterList contains a list of SecretParameters
type SecretParameterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecretParameter `json:"items"`
}

// Repository type metadata.
var (
	SecretParameter_Kind             = "SecretParameter"
	SecretParameter_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecretParameter_Kind}.String()
	SecretParameter_KindAPIVersion   = SecretParameter_Kind + "." + CRDGroupVersion.String()
	SecretParameter_GroupVersionKind = CRDGroupVersion.WithKind(SecretParameter_Kind)
)

func init() {
	SchemeBuilder.Register(&SecretParameter{}, &SecretParameterList{})
}
