apiVersion: oos.alibabacloud.crossplane.io/v1alpha1
kind: SecretParameter
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/secretparameter
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: terraform-example
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: us-west-1
    secretParameterName: crossplane-example-secretparameter
    tags:
      Created: TF
      For: OosSecretParameter
    type: Secret
    valueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: kms.alibabacloud.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/secretparameter
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: terraform-example
    pendingWindowInDays: 7
    region: us-west-1
    status: Enabled
