apiVersion: oos.alibabacloud.crossplane.io/v1alpha1
kind: ServiceSetting
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/servicesetting
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    deliveryOssBucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    deliveryOssEnabled: true
    deliveryOssKeyPrefix: path1/
    region: us-west-1

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/servicesetting
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucket: crossplane-example-oos-servicesetting
    region: us-west-1

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: oos/v1alpha1/servicesetting
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    acl: public-read-write
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: us-west-1
