// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Application) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ApplicationGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DefaultPatchBaseline) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Execution) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Parameter) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PatchBaseline) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretParameter) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceSetting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StateConfiguration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Template) Hub() {}
