// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ServiceSettingInitParameters struct {

	// The name of the OSS bucket. NOTE: When the delivery_oss_enabled is true, The delivery_oss_bucket_name is valid.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/oss/v1alpha1.Bucket
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("bucket",false)
	DeliveryOssBucketName *string `json:"deliveryOssBucketName,omitempty" tf:"delivery_oss_bucket_name,omitempty"`

	// Reference to a Bucket in oss to populate deliveryOssBucketName.
	// +kubebuilder:validation:Optional
	DeliveryOssBucketNameRef *v1.NamespacedReference `json:"deliveryOssBucketNameRef,omitempty" tf:"-"`

	// Selector for a Bucket in oss to populate deliveryOssBucketName.
	// +kubebuilder:validation:Optional
	DeliveryOssBucketNameSelector *v1.NamespacedSelector `json:"deliveryOssBucketNameSelector,omitempty" tf:"-"`

	// Is the recording function for the OSS delivery template enabled.
	DeliveryOssEnabled *bool `json:"deliveryOssEnabled,omitempty" tf:"delivery_oss_enabled,omitempty"`

	// The Directory of the OSS bucket. NOTE: When the delivery_oss_enabled is true, The delivery_oss_bucket_name is valid.
	DeliveryOssKeyPrefix *string `json:"deliveryOssKeyPrefix,omitempty" tf:"delivery_oss_key_prefix,omitempty"`

	// Is the execution record function to SLS delivery Template turned on.
	DeliverySlsEnabled *bool `json:"deliverySlsEnabled,omitempty" tf:"delivery_sls_enabled,omitempty"`

	// The name of SLS  Project. NOTE: When the delivery_sls_enabled is true, The delivery_sls_project_name is valid.
	DeliverySlsProjectName *string `json:"deliverySlsProjectName,omitempty" tf:"delivery_sls_project_name,omitempty"`
}

type ServiceSettingObservation struct {

	// The name of the OSS bucket. NOTE: When the delivery_oss_enabled is true, The delivery_oss_bucket_name is valid.
	DeliveryOssBucketName *string `json:"deliveryOssBucketName,omitempty" tf:"delivery_oss_bucket_name,omitempty"`

	// Is the recording function for the OSS delivery template enabled.
	DeliveryOssEnabled *bool `json:"deliveryOssEnabled,omitempty" tf:"delivery_oss_enabled,omitempty"`

	// The Directory of the OSS bucket. NOTE: When the delivery_oss_enabled is true, The delivery_oss_bucket_name is valid.
	DeliveryOssKeyPrefix *string `json:"deliveryOssKeyPrefix,omitempty" tf:"delivery_oss_key_prefix,omitempty"`

	// Is the execution record function to SLS delivery Template turned on.
	DeliverySlsEnabled *bool `json:"deliverySlsEnabled,omitempty" tf:"delivery_sls_enabled,omitempty"`

	// The name of SLS  Project. NOTE: When the delivery_sls_enabled is true, The delivery_sls_project_name is valid.
	DeliverySlsProjectName *string `json:"deliverySlsProjectName,omitempty" tf:"delivery_sls_project_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ServiceSettingParameters struct {

	// The name of the OSS bucket. NOTE: When the delivery_oss_enabled is true, The delivery_oss_bucket_name is valid.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/oss/v1alpha1.Bucket
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("bucket",false)
	// +kubebuilder:validation:Optional
	DeliveryOssBucketName *string `json:"deliveryOssBucketName,omitempty" tf:"delivery_oss_bucket_name,omitempty"`

	// Reference to a Bucket in oss to populate deliveryOssBucketName.
	// +kubebuilder:validation:Optional
	DeliveryOssBucketNameRef *v1.NamespacedReference `json:"deliveryOssBucketNameRef,omitempty" tf:"-"`

	// Selector for a Bucket in oss to populate deliveryOssBucketName.
	// +kubebuilder:validation:Optional
	DeliveryOssBucketNameSelector *v1.NamespacedSelector `json:"deliveryOssBucketNameSelector,omitempty" tf:"-"`

	// Is the recording function for the OSS delivery template enabled.
	// +kubebuilder:validation:Optional
	DeliveryOssEnabled *bool `json:"deliveryOssEnabled,omitempty" tf:"delivery_oss_enabled,omitempty"`

	// The Directory of the OSS bucket. NOTE: When the delivery_oss_enabled is true, The delivery_oss_bucket_name is valid.
	// +kubebuilder:validation:Optional
	DeliveryOssKeyPrefix *string `json:"deliveryOssKeyPrefix,omitempty" tf:"delivery_oss_key_prefix,omitempty"`

	// Is the execution record function to SLS delivery Template turned on.
	// +kubebuilder:validation:Optional
	DeliverySlsEnabled *bool `json:"deliverySlsEnabled,omitempty" tf:"delivery_sls_enabled,omitempty"`

	// The name of SLS  Project. NOTE: When the delivery_sls_enabled is true, The delivery_sls_project_name is valid.
	// +kubebuilder:validation:Optional
	DeliverySlsProjectName *string `json:"deliverySlsProjectName,omitempty" tf:"delivery_sls_project_name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// ServiceSettingSpec defines the desired state of ServiceSetting
type ServiceSettingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServiceSettingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceSettingInitParameters `json:"initProvider,omitempty"`
}

// ServiceSettingStatus defines the observed state of ServiceSetting.
type ServiceSettingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceSettingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceSetting is the Schema for the ServiceSettings API. Provides a Alicloud OOS Service Setting resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,alibabacloud}
type ServiceSetting struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ServiceSettingSpec   `json:"spec"`
	Status            ServiceSettingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceSettingList contains a list of ServiceSettings
type ServiceSettingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceSetting `json:"items"`
}

// Repository type metadata.
var (
	ServiceSetting_Kind             = "ServiceSetting"
	ServiceSetting_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceSetting_Kind}.String()
	ServiceSetting_KindAPIVersion   = ServiceSetting_Kind + "." + CRDGroupVersion.String()
	ServiceSetting_GroupVersionKind = CRDGroupVersion.WithKind(ServiceSetting_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceSetting{}, &ServiceSettingList{})
}
