// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TemplateInitParameters struct {

	// When deleting a template, whether to delete its related executions. Default to false.
	AutoDeleteExecutions *bool `json:"autoDeleteExecutions,omitempty" tf:"auto_delete_executions,omitempty"`

	// The content of the template. The template must be in the JSON or YAML format. Maximum size: 64 KB.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// The ID of resource group which the template belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The name of the template. The template name can be up to 200 characters in length. The name can contain letters, digits, hyphens (-), and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, or ALICLOUD.
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The name of template version.
	VersionName *string `json:"versionName,omitempty" tf:"version_name,omitempty"`
}

type TemplateObservation struct {

	// When deleting a template, whether to delete its related executions. Default to false.
	AutoDeleteExecutions *bool `json:"autoDeleteExecutions,omitempty" tf:"auto_delete_executions,omitempty"`

	// The content of the template. The template must be in the JSON or YAML format. Maximum size: 64 KB.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// The creator of the template.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// The time when the template is created.
	CreatedDate *string `json:"createdDate,omitempty" tf:"created_date,omitempty"`

	// The description of the template.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Is it triggered successfully.
	HasTrigger *bool `json:"hasTrigger,omitempty" tf:"has_trigger,omitempty"`

	// The id of the resource. It same with template_name.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of resource group which the template belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// The sharing type of the template. The sharing type of templates created by users are set to Private. The sharing type of common templates provided by OOS are set to Public.
	ShareType *string `json:"shareType,omitempty" tf:"share_type,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The format of the template. The format can be JSON or YAML. The system automatically identifies the format.
	TemplateFormat *string `json:"templateFormat,omitempty" tf:"template_format,omitempty"`

	// The id of OOS Template.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// The name of the template. The template name can be up to 200 characters in length. The name can contain letters, digits, hyphens (-), and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, or ALICLOUD.
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The type of OOS Template. Automation means the implementation of Alibaba Cloud API template, Package means represents a template for installing software.
	TemplateType *string `json:"templateType,omitempty" tf:"template_type,omitempty"`

	// The version of OOS Template.
	TemplateVersion *string `json:"templateVersion,omitempty" tf:"template_version,omitempty"`

	// The user who updated the template.
	UpdatedBy *string `json:"updatedBy,omitempty" tf:"updated_by,omitempty"`

	// The time when the template was updated.
	UpdatedDate *string `json:"updatedDate,omitempty" tf:"updated_date,omitempty"`

	// The name of template version.
	VersionName *string `json:"versionName,omitempty" tf:"version_name,omitempty"`
}

type TemplateParameters struct {

	// When deleting a template, whether to delete its related executions. Default to false.
	// +kubebuilder:validation:Optional
	AutoDeleteExecutions *bool `json:"autoDeleteExecutions,omitempty" tf:"auto_delete_executions,omitempty"`

	// The content of the template. The template must be in the JSON or YAML format. Maximum size: 64 KB.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of resource group which the template belongs.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The name of the template. The template name can be up to 200 characters in length. The name can contain letters, digits, hyphens (-), and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, or ALICLOUD.
	// +kubebuilder:validation:Optional
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// The name of template version.
	// +kubebuilder:validation:Optional
	VersionName *string `json:"versionName,omitempty" tf:"version_name,omitempty"`
}

// TemplateSpec defines the desired state of Template
type TemplateSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TemplateInitParameters `json:"initProvider,omitempty"`
}

// TemplateStatus defines the observed state of Template.
type TemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Template is the Schema for the Templates API. Provides a OOS Template resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,alibabacloud}
type Template struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.content) || (has(self.initProvider) && has(self.initProvider.content))",message="spec.forProvider.content is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateName) || (has(self.initProvider) && has(self.initProvider.templateName))",message="spec.forProvider.templateName is a required parameter"
	Spec   TemplateSpec   `json:"spec"`
	Status TemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TemplateList contains a list of Templates
type TemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Template `json:"items"`
}

// Repository type metadata.
var (
	Template_Kind             = "Template"
	Template_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Template_Kind}.String()
	Template_KindAPIVersion   = Template_Kind + "." + CRDGroupVersion.String()
	Template_GroupVersionKind = CRDGroupVersion.WithKind(Template_Kind)
)

func init() {
	SchemeBuilder.Register(&Template{}, &TemplateList{})
}
