// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type EndpointACLPolicyInitParameters struct {

	// The description of the entry.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The type of endpoint. Valid values: internet.
	EndpointType *string `json:"endpointType,omitempty" tf:"endpoint_type,omitempty"`

	// The IP segment that allowed to access.
	Entry *string `json:"entry,omitempty" tf:"entry,omitempty"`

	// The ID of the CR Instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The module that needs to set the access policy. Valid values: Registry.
	ModuleName *string `json:"moduleName,omitempty" tf:"module_name,omitempty"`
}

type EndpointACLPolicyObservation struct {

	// The description of the entry.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The type of endpoint. Valid values: internet.
	EndpointType *string `json:"endpointType,omitempty" tf:"endpoint_type,omitempty"`

	// The IP segment that allowed to access.
	Entry *string `json:"entry,omitempty" tf:"entry,omitempty"`

	// The resource ID of Endpoint Acl Policy. The value formats as <instance_id>:<endpoint_type>:<entry>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the CR Instance.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The module that needs to set the access policy. Valid values: Registry.
	ModuleName *string `json:"moduleName,omitempty" tf:"module_name,omitempty"`
}

type EndpointACLPolicyParameters struct {

	// The description of the entry.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The type of endpoint. Valid values: internet.
	// +kubebuilder:validation:Optional
	EndpointType *string `json:"endpointType,omitempty" tf:"endpoint_type,omitempty"`

	// The IP segment that allowed to access.
	// +kubebuilder:validation:Optional
	Entry *string `json:"entry,omitempty" tf:"entry,omitempty"`

	// The ID of the CR Instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The module that needs to set the access policy. Valid values: Registry.
	// +kubebuilder:validation:Optional
	ModuleName *string `json:"moduleName,omitempty" tf:"module_name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// EndpointACLPolicySpec defines the desired state of EndpointACLPolicy
type EndpointACLPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            EndpointACLPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EndpointACLPolicyInitParameters `json:"initProvider,omitempty"`
}

// EndpointACLPolicyStatus defines the observed state of EndpointACLPolicy.
type EndpointACLPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EndpointACLPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EndpointACLPolicy is the Schema for the EndpointACLPolicys API. Provides a Alicloud CR Endpoint Acl Policy resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,alibabacloud}
type EndpointACLPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endpointType) || (has(self.initProvider) && has(self.initProvider.endpointType))",message="spec.forProvider.endpointType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entry) || (has(self.initProvider) && has(self.initProvider.entry))",message="spec.forProvider.entry is a required parameter"
	Spec   EndpointACLPolicySpec   `json:"spec"`
	Status EndpointACLPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EndpointACLPolicyList contains a list of EndpointACLPolicys
type EndpointACLPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EndpointACLPolicy `json:"items"`
}

// Repository type metadata.
var (
	EndpointACLPolicy_Kind             = "EndpointACLPolicy"
	EndpointACLPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EndpointACLPolicy_Kind}.String()
	EndpointACLPolicy_KindAPIVersion   = EndpointACLPolicy_Kind + "." + CRDGroupVersion.String()
	EndpointACLPolicy_GroupVersionKind = CRDGroupVersion.WithKind(EndpointACLPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&EndpointACLPolicy{}, &EndpointACLPolicyList{})
}
