// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type EeNamespaceInitParameters struct {

	// Specifies whether to automatically create an image repository in the namespace. Default value: false. Valid values: true, false.
	AutoCreate *bool `json:"autoCreate,omitempty" tf:"auto_create,omitempty"`

	// The default type of the repository that is automatically created. Valid values:
	DefaultVisibility *string `json:"defaultVisibility,omitempty" tf:"default_visibility,omitempty"`

	// The ID of the Container Registry Enterprise Edition instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The name of the Container Registry Enterprise Edition Name. It must be 2 to 120 characters in length, and can contain lowercase letters, digits, underscores (_), hyphens (-), and periods (.). It cannot start or end with a delimiter.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EeNamespaceObservation struct {

	// Specifies whether to automatically create an image repository in the namespace. Default value: false. Valid values: true, false.
	AutoCreate *bool `json:"autoCreate,omitempty" tf:"auto_create,omitempty"`

	// The default type of the repository that is automatically created. Valid values:
	DefaultVisibility *string `json:"defaultVisibility,omitempty" tf:"default_visibility,omitempty"`

	// It formats as <instance_id>:<name>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the Container Registry Enterprise Edition instance.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The name of the Container Registry Enterprise Edition Name. It must be 2 to 120 characters in length, and can contain lowercase letters, digits, underscores (_), hyphens (-), and periods (.). It cannot start or end with a delimiter.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EeNamespaceParameters struct {

	// Specifies whether to automatically create an image repository in the namespace. Default value: false. Valid values: true, false.
	// +kubebuilder:validation:Optional
	AutoCreate *bool `json:"autoCreate,omitempty" tf:"auto_create,omitempty"`

	// The default type of the repository that is automatically created. Valid values:
	// +kubebuilder:validation:Optional
	DefaultVisibility *string `json:"defaultVisibility,omitempty" tf:"default_visibility,omitempty"`

	// The ID of the Container Registry Enterprise Edition instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The name of the Container Registry Enterprise Edition Name. It must be 2 to 120 characters in length, and can contain lowercase letters, digits, underscores (_), hyphens (-), and periods (.). It cannot start or end with a delimiter.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// EeNamespaceSpec defines the desired state of EeNamespace
type EeNamespaceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            EeNamespaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EeNamespaceInitParameters `json:"initProvider,omitempty"`
}

// EeNamespaceStatus defines the observed state of EeNamespace.
type EeNamespaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EeNamespaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EeNamespace is the Schema for the EeNamespaces API. Provides a Alicloud Container Registry Enterprise Edition Namespace resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,alibabacloud}
type EeNamespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EeNamespaceSpec   `json:"spec"`
	Status EeNamespaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EeNamespaceList contains a list of EeNamespaces
type EeNamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EeNamespace `json:"items"`
}

// Repository type metadata.
var (
	EeNamespace_Kind             = "EeNamespace"
	EeNamespace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EeNamespace_Kind}.String()
	EeNamespace_KindAPIVersion   = EeNamespace_Kind + "." + CRDGroupVersion.String()
	EeNamespace_GroupVersionKind = CRDGroupVersion.WithKind(EeNamespace_Kind)
)

func init() {
	SchemeBuilder.Register(&EeNamespace{}, &EeNamespaceList{})
}
