// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RegistryNamespaceInitParameters struct {

	// Boolean, when it set to true, repositories are automatically created when pushing new images. If it set to false, you create repository for images before pushing.
	AutoCreate *bool `json:"autoCreate,omitempty" tf:"auto_create,omitempty"`

	// PUBLIC or PRIVATE, default repository visibility in this namespace.
	DefaultVisibility *string `json:"defaultVisibility,omitempty" tf:"default_visibility,omitempty"`

	// Name of Container Registry namespace.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type RegistryNamespaceObservation struct {

	// Boolean, when it set to true, repositories are automatically created when pushing new images. If it set to false, you create repository for images before pushing.
	AutoCreate *bool `json:"autoCreate,omitempty" tf:"auto_create,omitempty"`

	// PUBLIC or PRIVATE, default repository visibility in this namespace.
	DefaultVisibility *string `json:"defaultVisibility,omitempty" tf:"default_visibility,omitempty"`

	// The id of Container Registry namespace. The value is same as its name.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of Container Registry namespace.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type RegistryNamespaceParameters struct {

	// Boolean, when it set to true, repositories are automatically created when pushing new images. If it set to false, you create repository for images before pushing.
	// +kubebuilder:validation:Optional
	AutoCreate *bool `json:"autoCreate,omitempty" tf:"auto_create,omitempty"`

	// PUBLIC or PRIVATE, default repository visibility in this namespace.
	// +kubebuilder:validation:Optional
	DefaultVisibility *string `json:"defaultVisibility,omitempty" tf:"default_visibility,omitempty"`

	// Name of Container Registry namespace.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// RegistryNamespaceSpec defines the desired state of RegistryNamespace
type RegistryNamespaceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RegistryNamespaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegistryNamespaceInitParameters `json:"initProvider,omitempty"`
}

// RegistryNamespaceStatus defines the observed state of RegistryNamespace.
type RegistryNamespaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RegistryNamespaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RegistryNamespace is the Schema for the RegistryNamespaces API. Provides a Alicloud resource to manage Container Registry namespaces.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,alibabacloud}
type RegistryNamespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.autoCreate) || (has(self.initProvider) && has(self.initProvider.autoCreate))",message="spec.forProvider.autoCreate is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.defaultVisibility) || (has(self.initProvider) && has(self.initProvider.defaultVisibility))",message="spec.forProvider.defaultVisibility is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RegistryNamespaceSpec   `json:"spec"`
	Status RegistryNamespaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegistryNamespaceList contains a list of RegistryNamespaces
type RegistryNamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RegistryNamespace `json:"items"`
}

// Repository type metadata.
var (
	RegistryNamespace_Kind             = "RegistryNamespace"
	RegistryNamespace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RegistryNamespace_Kind}.String()
	RegistryNamespace_KindAPIVersion   = RegistryNamespace_Kind + "." + CRDGroupVersion.String()
	RegistryNamespace_GroupVersionKind = CRDGroupVersion.WithKind(RegistryNamespace_Kind)
)

func init() {
	SchemeBuilder.Register(&RegistryNamespace{}, &RegistryNamespaceList{})
}
