// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RoutesInitParameters struct {

	// Endpoint Type.
	EndpointType *string `json:"endpointType,omitempty" tf:"endpoint_type,omitempty"`

	// Instance domain name.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.CrEeInstanceVPCDomainExtractor()
	InstanceDomain *string `json:"instanceDomain,omitempty" tf:"instance_domain,omitempty"`

	// Reference to a EeInstance in cr to populate instanceDomain.
	// +kubebuilder:validation:Optional
	InstanceDomainRef *v1.NamespacedReference `json:"instanceDomainRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceDomain.
	// +kubebuilder:validation:Optional
	InstanceDomainSelector *v1.NamespacedSelector `json:"instanceDomainSelector,omitempty" tf:"-"`

	// Storage domain name.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.CrEeInstanceOssStorageDomainExtractor()
	StorageDomain *string `json:"storageDomain,omitempty" tf:"storage_domain,omitempty"`

	// Reference to a EeInstance in cr to populate storageDomain.
	// +kubebuilder:validation:Optional
	StorageDomainRef *v1.NamespacedReference `json:"storageDomainRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate storageDomain.
	// +kubebuilder:validation:Optional
	StorageDomainSelector *v1.NamespacedSelector `json:"storageDomainSelector,omitempty" tf:"-"`
}

type RoutesObservation struct {

	// Endpoint Type.
	EndpointType *string `json:"endpointType,omitempty" tf:"endpoint_type,omitempty"`

	// Instance domain name.
	InstanceDomain *string `json:"instanceDomain,omitempty" tf:"instance_domain,omitempty"`

	// Storage domain name.
	StorageDomain *string `json:"storageDomain,omitempty" tf:"storage_domain,omitempty"`
}

type RoutesParameters struct {

	// Endpoint Type.
	// +kubebuilder:validation:Optional
	EndpointType *string `json:"endpointType" tf:"endpoint_type,omitempty"`

	// Instance domain name.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.CrEeInstanceVPCDomainExtractor()
	// +kubebuilder:validation:Optional
	InstanceDomain *string `json:"instanceDomain,omitempty" tf:"instance_domain,omitempty"`

	// Reference to a EeInstance in cr to populate instanceDomain.
	// +kubebuilder:validation:Optional
	InstanceDomainRef *v1.NamespacedReference `json:"instanceDomainRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceDomain.
	// +kubebuilder:validation:Optional
	InstanceDomainSelector *v1.NamespacedSelector `json:"instanceDomainSelector,omitempty" tf:"-"`

	// Storage domain name.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.CrEeInstanceOssStorageDomainExtractor()
	// +kubebuilder:validation:Optional
	StorageDomain *string `json:"storageDomain,omitempty" tf:"storage_domain,omitempty"`

	// Reference to a EeInstance in cr to populate storageDomain.
	// +kubebuilder:validation:Optional
	StorageDomainRef *v1.NamespacedReference `json:"storageDomainRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate storageDomain.
	// +kubebuilder:validation:Optional
	StorageDomainSelector *v1.NamespacedSelector `json:"storageDomainSelector,omitempty" tf:"-"`
}

type StorageDomainRoutingRuleInitParameters struct {

	// The ID of the Container Registry Instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Domain name routing entry See routes below.
	Routes []RoutesInitParameters `json:"routes,omitempty" tf:"routes,omitempty"`
}

type StorageDomainRoutingRuleObservation struct {

	// The creation time of the resource.
	CreateTime *float64 `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The ID of the resource supplied above.The value is formulated as <instance_id>:<rule_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the Container Registry Instance.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Domain name routing entry See routes below.
	Routes []RoutesObservation `json:"routes,omitempty" tf:"routes,omitempty"`

	// The ID of the Rule.
	RuleID *string `json:"ruleId,omitempty" tf:"rule_id,omitempty"`
}

type StorageDomainRoutingRuleParameters struct {

	// The ID of the Container Registry Instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/cr/v1alpha1.EeInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a EeInstance in cr to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// Domain name routing entry See routes below.
	// +kubebuilder:validation:Optional
	Routes []RoutesParameters `json:"routes,omitempty" tf:"routes,omitempty"`
}

// StorageDomainRoutingRuleSpec defines the desired state of StorageDomainRoutingRule
type StorageDomainRoutingRuleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            StorageDomainRoutingRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StorageDomainRoutingRuleInitParameters `json:"initProvider,omitempty"`
}

// StorageDomainRoutingRuleStatus defines the observed state of StorageDomainRoutingRule.
type StorageDomainRoutingRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StorageDomainRoutingRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StorageDomainRoutingRule is the Schema for the StorageDomainRoutingRules API. Provides a Alicloud CR Storage Domain Routing Rule resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,alibabacloud}
type StorageDomainRoutingRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routes) || (has(self.initProvider) && has(self.initProvider.routes))",message="spec.forProvider.routes is a required parameter"
	Spec   StorageDomainRoutingRuleSpec   `json:"spec"`
	Status StorageDomainRoutingRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageDomainRoutingRuleList contains a list of StorageDomainRoutingRules
type StorageDomainRoutingRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageDomainRoutingRule `json:"items"`
}

// Repository type metadata.
var (
	StorageDomainRoutingRule_Kind             = "StorageDomainRoutingRule"
	StorageDomainRoutingRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StorageDomainRoutingRule_Kind}.String()
	StorageDomainRoutingRule_KindAPIVersion   = StorageDomainRoutingRule_Kind + "." + CRDGroupVersion.String()
	StorageDomainRoutingRule_GroupVersionKind = CRDGroupVersion.WithKind(StorageDomainRoutingRule_Kind)
)

func init() {
	SchemeBuilder.Register(&StorageDomainRoutingRule{}, &StorageDomainRoutingRuleList{})
}
