// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ConsumerGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Instance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *InstanceAllowedIPAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SaslACL) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SaslUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ScheduledScalingRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Topic) Hub() {}
