// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ScheduledScalingRuleInitParameters struct {

	// The duration (unit: minutes) of a scheduled elastic task.
	DurationMinutes *float64 `json:"durationMinutes,omitempty" tf:"duration_minutes,omitempty"`

	// Enables or disables the scheduled task policy. Valid values:
	// -true: Enables the policy.
	// -false: Disables the policy.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The time when the scheduled policy starts to execute.
	FirstScheduledTime *float64 `json:"firstScheduledTime,omitempty" tf:"first_scheduled_time,omitempty"`

	// The instance ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/alikafka/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in alikafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in alikafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// When schedule_type is repeat, the parameter is required. Valid values:
	// -Daily: Daily scheduled task.
	// -Weekly: Weekly scheduled task.
	RepeatType *string `json:"repeatType,omitempty" tf:"repeat_type,omitempty"`

	// The scheduled elastic reserved production specification (unit: MB/s).
	ReservedPubFlow *float64 `json:"reservedPubFlow,omitempty" tf:"reserved_pub_flow,omitempty"`

	// The scheduled elastic reserved consumption specification (unit: MB/s).
	ReservedSubFlow *float64 `json:"reservedSubFlow,omitempty" tf:"reserved_sub_flow,omitempty"`

	// The name of the scheduled policy rule.
	RuleName *string `json:"ruleName,omitempty" tf:"rule_name,omitempty"`

	// The schedule type. Valid values:
	ScheduleType *string `json:"scheduleType,omitempty" tf:"schedule_type,omitempty"`

	// The time zone (Coordinated Universal Time).
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// The weekly types. Supports execution on multiple days. When repeat_type is set to Weekly, you need to input this parameter. Valid values: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.
	// +listType=set
	WeeklyTypes []*string `json:"weeklyTypes,omitempty" tf:"weekly_types,omitempty"`
}

type ScheduledScalingRuleObservation struct {

	// The duration (unit: minutes) of a scheduled elastic task.
	DurationMinutes *float64 `json:"durationMinutes,omitempty" tf:"duration_minutes,omitempty"`

	// Enables or disables the scheduled task policy. Valid values:
	// -true: Enables the policy.
	// -false: Disables the policy.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The time when the scheduled policy starts to execute.
	FirstScheduledTime *float64 `json:"firstScheduledTime,omitempty" tf:"first_scheduled_time,omitempty"`

	// The ID of the resource supplied above. The value is formulated as <instance_id>:<rule_name>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The instance ID.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// When schedule_type is repeat, the parameter is required. Valid values:
	// -Daily: Daily scheduled task.
	// -Weekly: Weekly scheduled task.
	RepeatType *string `json:"repeatType,omitempty" tf:"repeat_type,omitempty"`

	// The scheduled elastic reserved production specification (unit: MB/s).
	ReservedPubFlow *float64 `json:"reservedPubFlow,omitempty" tf:"reserved_pub_flow,omitempty"`

	// The scheduled elastic reserved consumption specification (unit: MB/s).
	ReservedSubFlow *float64 `json:"reservedSubFlow,omitempty" tf:"reserved_sub_flow,omitempty"`

	// The name of the scheduled policy rule.
	RuleName *string `json:"ruleName,omitempty" tf:"rule_name,omitempty"`

	// The schedule type. Valid values:
	ScheduleType *string `json:"scheduleType,omitempty" tf:"schedule_type,omitempty"`

	// The time zone (Coordinated Universal Time).
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// The weekly types. Supports execution on multiple days. When repeat_type is set to Weekly, you need to input this parameter. Valid values: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.
	// +listType=set
	WeeklyTypes []*string `json:"weeklyTypes,omitempty" tf:"weekly_types,omitempty"`
}

type ScheduledScalingRuleParameters struct {

	// The duration (unit: minutes) of a scheduled elastic task.
	// +kubebuilder:validation:Optional
	DurationMinutes *float64 `json:"durationMinutes,omitempty" tf:"duration_minutes,omitempty"`

	// Enables or disables the scheduled task policy. Valid values:
	// -true: Enables the policy.
	// -false: Disables the policy.
	// +kubebuilder:validation:Optional
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// The time when the scheduled policy starts to execute.
	// +kubebuilder:validation:Optional
	FirstScheduledTime *float64 `json:"firstScheduledTime,omitempty" tf:"first_scheduled_time,omitempty"`

	// The instance ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/cluster/alikafka/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-alibabacloud/config/common.IdExtractor()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in alikafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in alikafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// When schedule_type is repeat, the parameter is required. Valid values:
	// -Daily: Daily scheduled task.
	// -Weekly: Weekly scheduled task.
	// +kubebuilder:validation:Optional
	RepeatType *string `json:"repeatType,omitempty" tf:"repeat_type,omitempty"`

	// The scheduled elastic reserved production specification (unit: MB/s).
	// +kubebuilder:validation:Optional
	ReservedPubFlow *float64 `json:"reservedPubFlow,omitempty" tf:"reserved_pub_flow,omitempty"`

	// The scheduled elastic reserved consumption specification (unit: MB/s).
	// +kubebuilder:validation:Optional
	ReservedSubFlow *float64 `json:"reservedSubFlow,omitempty" tf:"reserved_sub_flow,omitempty"`

	// The name of the scheduled policy rule.
	// +kubebuilder:validation:Optional
	RuleName *string `json:"ruleName,omitempty" tf:"rule_name,omitempty"`

	// The schedule type. Valid values:
	// +kubebuilder:validation:Optional
	ScheduleType *string `json:"scheduleType,omitempty" tf:"schedule_type,omitempty"`

	// The time zone (Coordinated Universal Time).
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// The weekly types. Supports execution on multiple days. When repeat_type is set to Weekly, you need to input this parameter. Valid values: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.
	// +kubebuilder:validation:Optional
	// +listType=set
	WeeklyTypes []*string `json:"weeklyTypes,omitempty" tf:"weekly_types,omitempty"`
}

// ScheduledScalingRuleSpec defines the desired state of ScheduledScalingRule
type ScheduledScalingRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScheduledScalingRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScheduledScalingRuleInitParameters `json:"initProvider,omitempty"`
}

// ScheduledScalingRuleStatus defines the observed state of ScheduledScalingRule.
type ScheduledScalingRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScheduledScalingRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScheduledScalingRule is the Schema for the ScheduledScalingRules API. Provides a Alicloud Alikafka Scheduled Scaling Rule resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type ScheduledScalingRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.durationMinutes) || (has(self.initProvider) && has(self.initProvider.durationMinutes))",message="spec.forProvider.durationMinutes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.firstScheduledTime) || (has(self.initProvider) && has(self.initProvider.firstScheduledTime))",message="spec.forProvider.firstScheduledTime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.reservedPubFlow) || (has(self.initProvider) && has(self.initProvider.reservedPubFlow))",message="spec.forProvider.reservedPubFlow is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.reservedSubFlow) || (has(self.initProvider) && has(self.initProvider.reservedSubFlow))",message="spec.forProvider.reservedSubFlow is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ruleName) || (has(self.initProvider) && has(self.initProvider.ruleName))",message="spec.forProvider.ruleName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scheduleType) || (has(self.initProvider) && has(self.initProvider.scheduleType))",message="spec.forProvider.scheduleType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.timeZone) || (has(self.initProvider) && has(self.initProvider.timeZone))",message="spec.forProvider.timeZone is a required parameter"
	Spec   ScheduledScalingRuleSpec   `json:"spec"`
	Status ScheduledScalingRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScheduledScalingRuleList contains a list of ScheduledScalingRules
type ScheduledScalingRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScheduledScalingRule `json:"items"`
}

// Repository type metadata.
var (
	ScheduledScalingRule_Kind             = "ScheduledScalingRule"
	ScheduledScalingRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScheduledScalingRule_Kind}.String()
	ScheduledScalingRule_KindAPIVersion   = ScheduledScalingRule_Kind + "." + CRDGroupVersion.String()
	ScheduledScalingRule_GroupVersionKind = CRDGroupVersion.WithKind(ScheduledScalingRule_Kind)
)

func init() {
	SchemeBuilder.Register(&ScheduledScalingRule{}, &ScheduledScalingRuleList{})
}
