// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DeleteOptionsInitParameters struct {

	// The deletion mode of the cluster. Different resources may have different default behavior, see resource_type for details. Valid values:
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// The type of resources that are created by cluster. Valid values:
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`
}

type DeleteOptionsObservation struct {

	// The deletion mode of the cluster. Different resources may have different default behavior, see resource_type for details. Valid values:
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// The type of resources that are created by cluster. Valid values:
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`
}

type DeleteOptionsParameters struct {

	// The deletion mode of the cluster. Different resources may have different default behavior, see resource_type for details. Valid values:
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// The type of resources that are created by cluster. Valid values:
	// +kubebuilder:validation:Optional
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`
}

type KubernetesAddonsInitParameters struct {

	// The ACK add-on configurations. For more config information, see cs_kubernetes_addon_metadata.
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// Disables the automatic installation of a component. Default is false.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Name of the ACK add-on. The name must match one of the names returned by DescribeAddons.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The version of the component.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KubernetesAddonsObservation struct {

	// The ACK add-on configurations. For more config information, see cs_kubernetes_addon_metadata.
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// Disables the automatic installation of a component. Default is false.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Name of the ACK add-on. The name must match one of the names returned by DescribeAddons.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The version of the component.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KubernetesAddonsParameters struct {

	// The ACK add-on configurations. For more config information, see cs_kubernetes_addon_metadata.
	// +kubebuilder:validation:Optional
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// Disables the automatic installation of a component. Default is false.
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Name of the ACK add-on. The name must match one of the names returned by DescribeAddons.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The version of the component.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KubernetesCertificateAuthorityInitParameters struct {
}

type KubernetesCertificateAuthorityObservation struct {

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.client_cert attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/client-cert.pem) for replace it.
	ClientCert *string `json:"clientCert,omitempty" tf:"client_cert,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.client_key attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/client-key.pem) for replace it.
	ClientKey *string `json:"clientKey,omitempty" tf:"client_key,omitempty"`

	// The base64 encoded cluster certificate data required to communicate with your cluster. Add this to the certificate-authority-data section of the kubeconfig file for your cluster.
	ClusterCert *string `json:"clusterCert,omitempty" tf:"cluster_cert,omitempty"`
}

type KubernetesCertificateAuthorityParameters struct {
}

type KubernetesConnectionsInitParameters struct {
}

type KubernetesConnectionsObservation struct {

	// API Server Internet endpoint.
	APIServerInternet *string `json:"apiServerInternet,omitempty" tf:"api_server_internet,omitempty"`

	// API Server Intranet endpoint.
	APIServerIntranet *string `json:"apiServerIntranet,omitempty" tf:"api_server_intranet,omitempty"`

	// Master node SSH IP address.
	MasterPublicIP *string `json:"masterPublicIp,omitempty" tf:"master_public_ip,omitempty"`

	// Service Access Domain.
	ServiceDomain *string `json:"serviceDomain,omitempty" tf:"service_domain,omitempty"`
}

type KubernetesConnectionsParameters struct {
}

type KubernetesInitParameters struct {

	// A list of API audiences for Service Account Token Volume Projection. Set this to ["https://kubernetes.default.svc"] if you want to enable the Token Volume Projection feature requires specifying service_account_issuer as well. From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	APIAudiences []*string `json:"apiAudiences,omitempty" tf:"api_audiences,omitempty"`

	// The addon you want to install in cluster. See addons below. Only works for Create Operation, use resource cs_kubernetes_addon to manage addons if cluster is created.
	Addons []KubernetesAddonsInitParameters `json:"addons,omitempty" tf:"addons,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.client_cert attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/client-cert.pem) for replace it.
	ClientCert *string `json:"clientCert,omitempty" tf:"client_cert,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.client_key attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/client-key.pem) for replace it.
	ClientKey *string `json:"clientKey,omitempty" tf:"client_key,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.cluster_cert attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/cluster-ca-cert.pem) for replace it.
	ClusterCACert *string `json:"clusterCaCert,omitempty" tf:"cluster_ca_cert,omitempty"`

	// Cluster local domain name, Default to cluster.local. A domain name consists of one or more sections separated by a decimal point (.), each of which is up to 63 characters long, and can be lowercase, numerals, and underscores (-), and must be lowercase or numerals at the beginning and end.
	// cluster local domain
	ClusterDomain *string `json:"clusterDomain,omitempty" tf:"cluster_domain,omitempty"`

	// Customize the certificate SAN, multiple IP or domain names are separated by English commas (,).
	CustomSan *string `json:"customSan,omitempty" tf:"custom_san,omitempty"`

	// Delete options, only work for deleting resource. See delete_options below.
	DeleteOptions []DeleteOptionsInitParameters `json:"deleteOptions,omitempty" tf:"delete_options,omitempty"`

	// Whether to enable cluster deletion protection.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Enable login to the node through SSH. Default to false.
	EnableSSH *bool `json:"enableSsh,omitempty" tf:"enable_ssh,omitempty"`

	// Custom Image support. Must be based on AliyunLinux or AliyunLinux3.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Install cloud monitor agent on ECS. Default to true.
	InstallCloudMonitor *bool `json:"installCloudMonitor,omitempty" tf:"install_cloud_monitor,omitempty"`

	// Enable to create advanced security group. default: false. See Advanced security group. Only works for Create Operation.
	IsEnterpriseSecurityGroup *bool `json:"isEnterpriseSecurityGroup,omitempty" tf:"is_enterprise_security_group,omitempty"`

	// An KMS encrypts password used to a cs kubernetes. You have to specify one of password key_name kms_encrypted_password fields.
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a cs kubernetes with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The keypair of ssh login cluster node, you have to create it first. You have to specify one of password key_name kms_encrypted_password fields.
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// The cluster api server load balancer instance specification. For more information on how to select a LB instance specification, see SLB instance overview. Only works for Create Operation. The spec will not take effect because the charge of the load balancer has been changed to PayByCLCU.
	LoadBalancerSpec *string `json:"loadBalancerSpec,omitempty" tf:"load_balancer_spec,omitempty"`

	// Enable master payment auto-renew, defaults to false.
	MasterAutoRenew *bool `json:"masterAutoRenew,omitempty" tf:"master_auto_renew,omitempty"`

	// Master payment auto-renew period, it can be one of {1, 2, 3, 6, 12}.
	MasterAutoRenewPeriod *float64 `json:"masterAutoRenewPeriod,omitempty" tf:"master_auto_renew_period,omitempty"`

	// The system disk category of master node. Its valid value are cloud_ssd, cloud_essd and cloud_efficiency. Default to cloud_efficiency.
	MasterDiskCategory *string `json:"masterDiskCategory,omitempty" tf:"master_disk_category,omitempty"`

	// Master node system disk performance level. When master_disk_category values cloud_essd, the optional values are PL0, PL1, PL2 or PL3, but the specific performance level is related to the disk capacity. For more information, see Enhanced SSDs. Default is PL1.
	MasterDiskPerformanceLevel *string `json:"masterDiskPerformanceLevel,omitempty" tf:"master_disk_performance_level,omitempty"`

	// The system disk size of master node. Its valid value range [20~500] in GB. Default to 20.
	MasterDiskSize *float64 `json:"masterDiskSize,omitempty" tf:"master_disk_size,omitempty"`

	// Master node system disk auto snapshot policy.
	MasterDiskSnapshotPolicyID *string `json:"masterDiskSnapshotPolicyId,omitempty" tf:"master_disk_snapshot_policy_id,omitempty"`

	// Master payment type. or PostPaid or PrePaid, defaults to PostPaid. If value is PrePaid, the files master_period, master_period_unit, master_auto_renew and master_auto_renew_period are required.
	MasterInstanceChargeType *string `json:"masterInstanceChargeType,omitempty" tf:"master_instance_charge_type,omitempty"`

	// The instance type of master node. Specify one type for single AZ Cluster, three types for MultiAZ Cluster.
	MasterInstanceTypes []*string `json:"masterInstanceTypes,omitempty" tf:"master_instance_types,omitempty"`

	// Master payment period.Its valid value is one of {1, 2, 3, 6, 12, 24, 36, 48, 60}.
	MasterPeriod *float64 `json:"masterPeriod,omitempty" tf:"master_period,omitempty"`

	// Master payment period unit, the valid value is Month.
	MasterPeriodUnit *string `json:"masterPeriodUnit,omitempty" tf:"master_period_unit,omitempty"`

	// The vswitches used by master, you can specific 3 or 5 vswitches because of the amount of masters. Detailed below.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/vpc/v1alpha1.Vswitch
	MasterVswitchIds []*string `json:"masterVswitchIds,omitempty" tf:"master_vswitch_ids,omitempty"`

	// References to Vswitch in vpc to populate masterVswitchIds.
	// +kubebuilder:validation:Optional
	MasterVswitchIdsRefs []v1.NamespacedReference `json:"masterVswitchIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Vswitch in vpc to populate masterVswitchIds.
	// +kubebuilder:validation:Optional
	MasterVswitchIdsSelector *v1.NamespacedSelector `json:"masterVswitchIdsSelector,omitempty" tf:"-"`

	// The kubernetes cluster's name. It is unique in one Alicloud account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether to create a new nat gateway while creating kubernetes cluster. Default to true. Then openapi in Alibaba Cloud are not all on intranet, So turn this option on is a good choice. Your cluster nodes and applications will have public network access. If there is a NAT gateway in the selected VPC, ACK will use this gateway by default; if there is no NAT gateway in the selected VPC, ACK will create a new NAT gateway for you and automatically configure SNAT rules. Only works for Create Operation.
	NewNATGateway *bool `json:"newNatGateway,omitempty" tf:"new_nat_gateway,omitempty"`

	// The node cidr block to specific how many pods can run on single node. 24-28 is allowed. 24 means 2^(32-24)-1=255 and the node can run at most 255 pods. default: 24
	NodeCidrMask *float64 `json:"nodeCidrMask,omitempty" tf:"node_cidr_mask,omitempty"`

	// Each node name consists of a prefix, an IP substring, and a suffix, the input format is customized,<prefix>,IPSubStringLen,<suffix>. For example "customized,aliyun.com-,5,-test", if the node IP address is 192.168.59.176, the prefix is aliyun.com-, IP substring length is 5, and the suffix is -test, the node name will be aliyun.com-59176-test.
	NodeNameMode *string `json:"nodeNameMode,omitempty" tf:"node_name_mode,omitempty"`

	// The operating system of the nodes that run pods, its valid value is either Linux or Windows. Default to Linux.
	OsType *string `json:"osType,omitempty" tf:"os_type,omitempty"`

	// The password of ssh login cluster node. You have to specify one of password key_name kms_encrypted_password fields.
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The architecture of the nodes that run pods, its valid value AliyunLinux, AliyunLinux3. Default to AliyunLinux3.
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// [Flannel Specific] The CIDR block for the pod network when using Flannel.
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// - [Terway Specific] The vswitches for the pod network when using Terway. It is recommended that pod_vswitch_ids is not belong to worker_vswitch_ids and master_vswitch_ids but must be in same availability zones. Only works for Create Operation.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/vpc/v1alpha1.Vswitch
	PodVswitchIds []*string `json:"podVswitchIds,omitempty" tf:"pod_vswitch_ids,omitempty"`

	// References to Vswitch in vpc to populate podVswitchIds.
	// +kubebuilder:validation:Optional
	PodVswitchIdsRefs []v1.NamespacedReference `json:"podVswitchIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Vswitch in vpc to populate podVswitchIds.
	// +kubebuilder:validation:Optional
	PodVswitchIdsSelector *v1.NamespacedSelector `json:"podVswitchIdsSelector,omitempty" tf:"-"`

	// kube-proxy proxy mode. Default: ipvs. Options: iptables, ipvs, nftables.
	ProxyMode *string `json:"proxyMode,omitempty" tf:"proxy_mode,omitempty"`

	// RDS instance list, You can choose which RDS instances whitelist to add instances to.
	RDSInstances []*string `json:"rdsInstances,omitempty" tf:"rds_instances,omitempty"`

	// The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Resources that are automatically created during cluster creation, including NAT gateways, SNAT rules, SLB instances, and RAM Role, will be deleted. Resources that are manually created after you create the cluster, such as SLB instances for Services, will also be deleted. If you need to retain resources, please configure with retain_resources. There are several aspects to pay attention to when using retain_resources to retain resources.
	RetainResources []*string `json:"retainResources,omitempty" tf:"retain_resources,omitempty"`

	// A list of runtime containers. If you select another container runtime, see How do I select between Docker and Sandboxed-Container. See runtime below.
	Runtime []KubernetesRuntimeInitParameters `json:"runtime,omitempty" tf:"runtime,omitempty"`

	// The ID of the security group to which the ECS instances in the cluster belong. If it is not specified, a new Security group will be built.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/ecs/v1alpha1.SecurityGroup
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// Reference to a SecurityGroup in ecs to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDRef *v1.NamespacedReference `json:"securityGroupIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in ecs to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDSelector *v1.NamespacedSelector `json:"securityGroupIdSelector,omitempty" tf:"-"`

	// The issuer of the Service Account token for Service Account Token Volume Projection, corresponds to the iss field in the token payload. Set this to "https://kubernetes.default.svc" to enable the Token Volume Projection feature (requires specifying api_audiences as well). From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	ServiceAccountIssuer *string `json:"serviceAccountIssuer,omitempty" tf:"service_account_issuer,omitempty"`

	// The CIDR block for the service network. It cannot be duplicated with the VPC CIDR and CIDR used by Kubernetes cluster in VPC, cannot be modified after creation.
	ServiceCidr *string `json:"serviceCidr,omitempty" tf:"service_cidr,omitempty"`

	// Configure whether to save certificate authority data for your cluster to attribute certificate_authority.For cluster security, recommended configuration as true. Will be removed with attribute certificate_authority removed.
	SkipSetCertificateAuthority *bool `json:"skipSetCertificateAuthority,omitempty" tf:"skip_set_certificate_authority,omitempty"`

	// Whether to create internet load balancer for API Server. Default to true. Only works for Create Operation.
	SlbInternetEnabled *bool `json:"slbInternetEnabled,omitempty" tf:"slb_internet_enabled,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// When you create a cluster, set the time zones for the Master and Worker nodes. You can only change the managed node time zone if you create a cluster. Once the cluster is created, you can only change the time zone of the Worker node.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The path of customized CA cert, you can use this CA to sign client certs to connect your cluster.
	UserCA *string `json:"userCa,omitempty" tf:"user_ca,omitempty"`

	// Desired Kubernetes version. If you do not specify a value, the latest available version at resource creation is used and no upgrades will occur except you set a higher version number. The value must be configured and increased to upgrade the version when desired. Downgrades are not supported by ACK.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KubernetesObservation struct {

	// A list of API audiences for Service Account Token Volume Projection. Set this to ["https://kubernetes.default.svc"] if you want to enable the Token Volume Projection feature requires specifying service_account_issuer as well. From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	APIAudiences []*string `json:"apiAudiences,omitempty" tf:"api_audiences,omitempty"`

	// The addon you want to install in cluster. See addons below. Only works for Create Operation, use resource cs_kubernetes_addon to manage addons if cluster is created.
	Addons []KubernetesAddonsObservation `json:"addons,omitempty" tf:"addons,omitempty"`

	// (List, Deprecated from v1.248.0) Nested attribute containing certificate authority data for your cluster. Please use the attribute certificate_authority of new DataSource alicloud_cs_cluster_credential to replace it.
	CertificateAuthority []KubernetesCertificateAuthorityObservation `json:"certificateAuthority,omitempty" tf:"certificate_authority,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.client_cert attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/client-cert.pem) for replace it.
	ClientCert *string `json:"clientCert,omitempty" tf:"client_cert,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.client_key attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/client-key.pem) for replace it.
	ClientKey *string `json:"clientKey,omitempty" tf:"client_key,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.cluster_cert attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/cluster-ca-cert.pem) for replace it.
	ClusterCACert *string `json:"clusterCaCert,omitempty" tf:"cluster_ca_cert,omitempty"`

	// Cluster local domain name, Default to cluster.local. A domain name consists of one or more sections separated by a decimal point (.), each of which is up to 63 characters long, and can be lowercase, numerals, and underscores (-), and must be lowercase or numerals at the beginning and end.
	// cluster local domain
	ClusterDomain *string `json:"clusterDomain,omitempty" tf:"cluster_domain,omitempty"`

	// (List) A list of kubernetes cluster connection information.
	Connections []KubernetesConnectionsObservation `json:"connections,omitempty" tf:"connections,omitempty"`

	// Customize the certificate SAN, multiple IP or domain names are separated by English commas (,).
	CustomSan *string `json:"customSan,omitempty" tf:"custom_san,omitempty"`

	// Delete options, only work for deleting resource. See delete_options below.
	DeleteOptions []DeleteOptionsObservation `json:"deleteOptions,omitempty" tf:"delete_options,omitempty"`

	// Whether to enable cluster deletion protection.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Enable login to the node through SSH. Default to false.
	EnableSSH *bool `json:"enableSsh,omitempty" tf:"enable_ssh,omitempty"`

	// The ID of the container cluster.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Custom Image support. Must be based on AliyunLinux or AliyunLinux3.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Install cloud monitor agent on ECS. Default to true.
	InstallCloudMonitor *bool `json:"installCloudMonitor,omitempty" tf:"install_cloud_monitor,omitempty"`

	// Enable to create advanced security group. default: false. See Advanced security group. Only works for Create Operation.
	IsEnterpriseSecurityGroup *bool `json:"isEnterpriseSecurityGroup,omitempty" tf:"is_enterprise_security_group,omitempty"`

	// An KMS encrypts password used to a cs kubernetes. You have to specify one of password key_name kms_encrypted_password fields.
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a cs kubernetes with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The keypair of ssh login cluster node, you have to create it first. You have to specify one of password key_name kms_encrypted_password fields.
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// The cluster api server load balancer instance specification. For more information on how to select a LB instance specification, see SLB instance overview. Only works for Create Operation. The spec will not take effect because the charge of the load balancer has been changed to PayByCLCU.
	LoadBalancerSpec *string `json:"loadBalancerSpec,omitempty" tf:"load_balancer_spec,omitempty"`

	// Enable master payment auto-renew, defaults to false.
	MasterAutoRenew *bool `json:"masterAutoRenew,omitempty" tf:"master_auto_renew,omitempty"`

	// Master payment auto-renew period, it can be one of {1, 2, 3, 6, 12}.
	MasterAutoRenewPeriod *float64 `json:"masterAutoRenewPeriod,omitempty" tf:"master_auto_renew_period,omitempty"`

	// The system disk category of master node. Its valid value are cloud_ssd, cloud_essd and cloud_efficiency. Default to cloud_efficiency.
	MasterDiskCategory *string `json:"masterDiskCategory,omitempty" tf:"master_disk_category,omitempty"`

	// Master node system disk performance level. When master_disk_category values cloud_essd, the optional values are PL0, PL1, PL2 or PL3, but the specific performance level is related to the disk capacity. For more information, see Enhanced SSDs. Default is PL1.
	MasterDiskPerformanceLevel *string `json:"masterDiskPerformanceLevel,omitempty" tf:"master_disk_performance_level,omitempty"`

	// The system disk size of master node. Its valid value range [20~500] in GB. Default to 20.
	MasterDiskSize *float64 `json:"masterDiskSize,omitempty" tf:"master_disk_size,omitempty"`

	// Master node system disk auto snapshot policy.
	MasterDiskSnapshotPolicyID *string `json:"masterDiskSnapshotPolicyId,omitempty" tf:"master_disk_snapshot_policy_id,omitempty"`

	// Master payment type. or PostPaid or PrePaid, defaults to PostPaid. If value is PrePaid, the files master_period, master_period_unit, master_auto_renew and master_auto_renew_period are required.
	MasterInstanceChargeType *string `json:"masterInstanceChargeType,omitempty" tf:"master_instance_charge_type,omitempty"`

	// The instance type of master node. Specify one type for single AZ Cluster, three types for MultiAZ Cluster.
	MasterInstanceTypes []*string `json:"masterInstanceTypes,omitempty" tf:"master_instance_types,omitempty"`

	// The master nodes. See master_nodes below.
	MasterNodes []MasterNodesObservation `json:"masterNodes,omitempty" tf:"master_nodes,omitempty"`

	// Master payment period.Its valid value is one of {1, 2, 3, 6, 12, 24, 36, 48, 60}.
	MasterPeriod *float64 `json:"masterPeriod,omitempty" tf:"master_period,omitempty"`

	// Master payment period unit, the valid value is Month.
	MasterPeriodUnit *string `json:"masterPeriodUnit,omitempty" tf:"master_period_unit,omitempty"`

	// The vswitches used by master, you can specific 3 or 5 vswitches because of the amount of masters. Detailed below.
	MasterVswitchIds []*string `json:"masterVswitchIds,omitempty" tf:"master_vswitch_ids,omitempty"`

	// The ID of nat gateway used to launch kubernetes cluster.
	NATGatewayID *string `json:"natGatewayId,omitempty" tf:"nat_gateway_id,omitempty"`

	// The kubernetes cluster's name. It is unique in one Alicloud account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether to create a new nat gateway while creating kubernetes cluster. Default to true. Then openapi in Alibaba Cloud are not all on intranet, So turn this option on is a good choice. Your cluster nodes and applications will have public network access. If there is a NAT gateway in the selected VPC, ACK will use this gateway by default; if there is no NAT gateway in the selected VPC, ACK will create a new NAT gateway for you and automatically configure SNAT rules. Only works for Create Operation.
	NewNATGateway *bool `json:"newNatGateway,omitempty" tf:"new_nat_gateway,omitempty"`

	// The node cidr block to specific how many pods can run on single node. 24-28 is allowed. 24 means 2^(32-24)-1=255 and the node can run at most 255 pods. default: 24
	NodeCidrMask *float64 `json:"nodeCidrMask,omitempty" tf:"node_cidr_mask,omitempty"`

	// Each node name consists of a prefix, an IP substring, and a suffix, the input format is customized,<prefix>,IPSubStringLen,<suffix>. For example "customized,aliyun.com-,5,-test", if the node IP address is 192.168.59.176, the prefix is aliyun.com-, IP substring length is 5, and the suffix is -test, the node name will be aliyun.com-59176-test.
	NodeNameMode *string `json:"nodeNameMode,omitempty" tf:"node_name_mode,omitempty"`

	// The operating system of the nodes that run pods, its valid value is either Linux or Windows. Default to Linux.
	OsType *string `json:"osType,omitempty" tf:"os_type,omitempty"`

	// The architecture of the nodes that run pods, its valid value AliyunLinux, AliyunLinux3. Default to AliyunLinux3.
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// [Flannel Specific] The CIDR block for the pod network when using Flannel.
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// - [Terway Specific] The vswitches for the pod network when using Terway. It is recommended that pod_vswitch_ids is not belong to worker_vswitch_ids and master_vswitch_ids but must be in same availability zones. Only works for Create Operation.
	PodVswitchIds []*string `json:"podVswitchIds,omitempty" tf:"pod_vswitch_ids,omitempty"`

	// kube-proxy proxy mode. Default: ipvs. Options: iptables, ipvs, nftables.
	ProxyMode *string `json:"proxyMode,omitempty" tf:"proxy_mode,omitempty"`

	// RDS instance list, You can choose which RDS instances whitelist to add instances to.
	RDSInstances []*string `json:"rdsInstances,omitempty" tf:"rds_instances,omitempty"`

	// The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Resources that are automatically created during cluster creation, including NAT gateways, SNAT rules, SLB instances, and RAM Role, will be deleted. Resources that are manually created after you create the cluster, such as SLB instances for Services, will also be deleted. If you need to retain resources, please configure with retain_resources. There are several aspects to pay attention to when using retain_resources to retain resources.
	RetainResources []*string `json:"retainResources,omitempty" tf:"retain_resources,omitempty"`

	// A list of runtime containers. If you select another container runtime, see How do I select between Docker and Sandboxed-Container. See runtime below.
	Runtime []KubernetesRuntimeObservation `json:"runtime,omitempty" tf:"runtime,omitempty"`

	// The ID of the security group to which the ECS instances in the cluster belong. If it is not specified, a new Security group will be built.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// The issuer of the Service Account token for Service Account Token Volume Projection, corresponds to the iss field in the token payload. Set this to "https://kubernetes.default.svc" to enable the Token Volume Projection feature (requires specifying api_audiences as well). From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	ServiceAccountIssuer *string `json:"serviceAccountIssuer,omitempty" tf:"service_account_issuer,omitempty"`

	// The CIDR block for the service network. It cannot be duplicated with the VPC CIDR and CIDR used by Kubernetes cluster in VPC, cannot be modified after creation.
	ServiceCidr *string `json:"serviceCidr,omitempty" tf:"service_cidr,omitempty"`

	// Configure whether to save certificate authority data for your cluster to attribute certificate_authority.For cluster security, recommended configuration as true. Will be removed with attribute certificate_authority removed.
	SkipSetCertificateAuthority *bool `json:"skipSetCertificateAuthority,omitempty" tf:"skip_set_certificate_authority,omitempty"`

	// The ID of APIServer load balancer.
	SlbID *string `json:"slbId,omitempty" tf:"slb_id,omitempty"`

	// The public ip of load balancer.
	SlbInternet *string `json:"slbInternet,omitempty" tf:"slb_internet,omitempty"`

	// Whether to create internet load balancer for API Server. Default to true. Only works for Create Operation.
	SlbInternetEnabled *bool `json:"slbInternetEnabled,omitempty" tf:"slb_internet_enabled,omitempty"`

	// The ID of private load balancer where the current cluster master node is located.
	SlbIntranet *string `json:"slbIntranet,omitempty" tf:"slb_intranet,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// When you create a cluster, set the time zones for the Master and Worker nodes. You can only change the managed node time zone if you create a cluster. Once the cluster is created, you can only change the time zone of the Worker node.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The path of customized CA cert, you can use this CA to sign client certs to connect your cluster.
	UserCA *string `json:"userCa,omitempty" tf:"user_ca,omitempty"`

	// The ID of VPC where the current cluster is located.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Desired Kubernetes version. If you do not specify a value, the latest available version at resource creation is used and no upgrades will occur except you set a higher version number. The value must be configured and increased to upgrade the version when desired. Downgrades are not supported by ACK.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// The RamRole Name attached to worker node.
	WorkerRAMRoleName *string `json:"workerRamRoleName,omitempty" tf:"worker_ram_role_name,omitempty"`
}

type KubernetesParameters struct {

	// A list of API audiences for Service Account Token Volume Projection. Set this to ["https://kubernetes.default.svc"] if you want to enable the Token Volume Projection feature requires specifying service_account_issuer as well. From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	// +kubebuilder:validation:Optional
	APIAudiences []*string `json:"apiAudiences,omitempty" tf:"api_audiences,omitempty"`

	// The addon you want to install in cluster. See addons below. Only works for Create Operation, use resource cs_kubernetes_addon to manage addons if cluster is created.
	// +kubebuilder:validation:Optional
	Addons []KubernetesAddonsParameters `json:"addons,omitempty" tf:"addons,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.client_cert attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/client-cert.pem) for replace it.
	// +kubebuilder:validation:Optional
	ClientCert *string `json:"clientCert,omitempty" tf:"client_cert,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.client_key attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/client-key.pem) for replace it.
	// +kubebuilder:validation:Optional
	ClientKey *string `json:"clientKey,omitempty" tf:"client_key,omitempty"`

	// From version 1.248.0, new DataSource alicloud_cs_cluster_credential is recommended to manage cluster's kubeconfig, you can also save the certificate_authority.cluster_cert attribute content of new DataSource alicloud_cs_cluster_credential to an appropriate path(like ~/.kube/cluster-ca-cert.pem) for replace it.
	// +kubebuilder:validation:Optional
	ClusterCACert *string `json:"clusterCaCert,omitempty" tf:"cluster_ca_cert,omitempty"`

	// Cluster local domain name, Default to cluster.local. A domain name consists of one or more sections separated by a decimal point (.), each of which is up to 63 characters long, and can be lowercase, numerals, and underscores (-), and must be lowercase or numerals at the beginning and end.
	// cluster local domain
	// +kubebuilder:validation:Optional
	ClusterDomain *string `json:"clusterDomain,omitempty" tf:"cluster_domain,omitempty"`

	// Customize the certificate SAN, multiple IP or domain names are separated by English commas (,).
	// +kubebuilder:validation:Optional
	CustomSan *string `json:"customSan,omitempty" tf:"custom_san,omitempty"`

	// Delete options, only work for deleting resource. See delete_options below.
	// +kubebuilder:validation:Optional
	DeleteOptions []DeleteOptionsParameters `json:"deleteOptions,omitempty" tf:"delete_options,omitempty"`

	// Whether to enable cluster deletion protection.
	// +kubebuilder:validation:Optional
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Enable login to the node through SSH. Default to false.
	// +kubebuilder:validation:Optional
	EnableSSH *bool `json:"enableSsh,omitempty" tf:"enable_ssh,omitempty"`

	// Custom Image support. Must be based on AliyunLinux or AliyunLinux3.
	// +kubebuilder:validation:Optional
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Install cloud monitor agent on ECS. Default to true.
	// +kubebuilder:validation:Optional
	InstallCloudMonitor *bool `json:"installCloudMonitor,omitempty" tf:"install_cloud_monitor,omitempty"`

	// Enable to create advanced security group. default: false. See Advanced security group. Only works for Create Operation.
	// +kubebuilder:validation:Optional
	IsEnterpriseSecurityGroup *bool `json:"isEnterpriseSecurityGroup,omitempty" tf:"is_enterprise_security_group,omitempty"`

	// An KMS encrypts password used to a cs kubernetes. You have to specify one of password key_name kms_encrypted_password fields.
	// +kubebuilder:validation:Optional
	KMSEncryptedPassword *string `json:"kmsEncryptedPassword,omitempty" tf:"kms_encrypted_password,omitempty"`

	// An KMS encryption context used to decrypt kms_encrypted_password before creating or updating a cs kubernetes with kms_encrypted_password. See Encryption Context. It is valid when kms_encrypted_password is set.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	KMSEncryptionContext map[string]*string `json:"kmsEncryptionContext,omitempty" tf:"kms_encryption_context,omitempty"`

	// The keypair of ssh login cluster node, you have to create it first. You have to specify one of password key_name kms_encrypted_password fields.
	// +kubebuilder:validation:Optional
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// The cluster api server load balancer instance specification. For more information on how to select a LB instance specification, see SLB instance overview. Only works for Create Operation. The spec will not take effect because the charge of the load balancer has been changed to PayByCLCU.
	// +kubebuilder:validation:Optional
	LoadBalancerSpec *string `json:"loadBalancerSpec,omitempty" tf:"load_balancer_spec,omitempty"`

	// Enable master payment auto-renew, defaults to false.
	// +kubebuilder:validation:Optional
	MasterAutoRenew *bool `json:"masterAutoRenew,omitempty" tf:"master_auto_renew,omitempty"`

	// Master payment auto-renew period, it can be one of {1, 2, 3, 6, 12}.
	// +kubebuilder:validation:Optional
	MasterAutoRenewPeriod *float64 `json:"masterAutoRenewPeriod,omitempty" tf:"master_auto_renew_period,omitempty"`

	// The system disk category of master node. Its valid value are cloud_ssd, cloud_essd and cloud_efficiency. Default to cloud_efficiency.
	// +kubebuilder:validation:Optional
	MasterDiskCategory *string `json:"masterDiskCategory,omitempty" tf:"master_disk_category,omitempty"`

	// Master node system disk performance level. When master_disk_category values cloud_essd, the optional values are PL0, PL1, PL2 or PL3, but the specific performance level is related to the disk capacity. For more information, see Enhanced SSDs. Default is PL1.
	// +kubebuilder:validation:Optional
	MasterDiskPerformanceLevel *string `json:"masterDiskPerformanceLevel,omitempty" tf:"master_disk_performance_level,omitempty"`

	// The system disk size of master node. Its valid value range [20~500] in GB. Default to 20.
	// +kubebuilder:validation:Optional
	MasterDiskSize *float64 `json:"masterDiskSize,omitempty" tf:"master_disk_size,omitempty"`

	// Master node system disk auto snapshot policy.
	// +kubebuilder:validation:Optional
	MasterDiskSnapshotPolicyID *string `json:"masterDiskSnapshotPolicyId,omitempty" tf:"master_disk_snapshot_policy_id,omitempty"`

	// Master payment type. or PostPaid or PrePaid, defaults to PostPaid. If value is PrePaid, the files master_period, master_period_unit, master_auto_renew and master_auto_renew_period are required.
	// +kubebuilder:validation:Optional
	MasterInstanceChargeType *string `json:"masterInstanceChargeType,omitempty" tf:"master_instance_charge_type,omitempty"`

	// The instance type of master node. Specify one type for single AZ Cluster, three types for MultiAZ Cluster.
	// +kubebuilder:validation:Optional
	MasterInstanceTypes []*string `json:"masterInstanceTypes,omitempty" tf:"master_instance_types,omitempty"`

	// Master payment period.Its valid value is one of {1, 2, 3, 6, 12, 24, 36, 48, 60}.
	// +kubebuilder:validation:Optional
	MasterPeriod *float64 `json:"masterPeriod,omitempty" tf:"master_period,omitempty"`

	// Master payment period unit, the valid value is Month.
	// +kubebuilder:validation:Optional
	MasterPeriodUnit *string `json:"masterPeriodUnit,omitempty" tf:"master_period_unit,omitempty"`

	// The vswitches used by master, you can specific 3 or 5 vswitches because of the amount of masters. Detailed below.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/vpc/v1alpha1.Vswitch
	// +kubebuilder:validation:Optional
	MasterVswitchIds []*string `json:"masterVswitchIds,omitempty" tf:"master_vswitch_ids,omitempty"`

	// References to Vswitch in vpc to populate masterVswitchIds.
	// +kubebuilder:validation:Optional
	MasterVswitchIdsRefs []v1.NamespacedReference `json:"masterVswitchIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Vswitch in vpc to populate masterVswitchIds.
	// +kubebuilder:validation:Optional
	MasterVswitchIdsSelector *v1.NamespacedSelector `json:"masterVswitchIdsSelector,omitempty" tf:"-"`

	// The kubernetes cluster's name. It is unique in one Alicloud account.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether to create a new nat gateway while creating kubernetes cluster. Default to true. Then openapi in Alibaba Cloud are not all on intranet, So turn this option on is a good choice. Your cluster nodes and applications will have public network access. If there is a NAT gateway in the selected VPC, ACK will use this gateway by default; if there is no NAT gateway in the selected VPC, ACK will create a new NAT gateway for you and automatically configure SNAT rules. Only works for Create Operation.
	// +kubebuilder:validation:Optional
	NewNATGateway *bool `json:"newNatGateway,omitempty" tf:"new_nat_gateway,omitempty"`

	// The node cidr block to specific how many pods can run on single node. 24-28 is allowed. 24 means 2^(32-24)-1=255 and the node can run at most 255 pods. default: 24
	// +kubebuilder:validation:Optional
	NodeCidrMask *float64 `json:"nodeCidrMask,omitempty" tf:"node_cidr_mask,omitempty"`

	// Each node name consists of a prefix, an IP substring, and a suffix, the input format is customized,<prefix>,IPSubStringLen,<suffix>. For example "customized,aliyun.com-,5,-test", if the node IP address is 192.168.59.176, the prefix is aliyun.com-, IP substring length is 5, and the suffix is -test, the node name will be aliyun.com-59176-test.
	// +kubebuilder:validation:Optional
	NodeNameMode *string `json:"nodeNameMode,omitempty" tf:"node_name_mode,omitempty"`

	// The operating system of the nodes that run pods, its valid value is either Linux or Windows. Default to Linux.
	// +kubebuilder:validation:Optional
	OsType *string `json:"osType,omitempty" tf:"os_type,omitempty"`

	// The password of ssh login cluster node. You have to specify one of password key_name kms_encrypted_password fields.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// The architecture of the nodes that run pods, its valid value AliyunLinux, AliyunLinux3. Default to AliyunLinux3.
	// +kubebuilder:validation:Optional
	Platform *string `json:"platform,omitempty" tf:"platform,omitempty"`

	// [Flannel Specific] The CIDR block for the pod network when using Flannel.
	// +kubebuilder:validation:Optional
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// - [Terway Specific] The vswitches for the pod network when using Terway. It is recommended that pod_vswitch_ids is not belong to worker_vswitch_ids and master_vswitch_ids but must be in same availability zones. Only works for Create Operation.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/vpc/v1alpha1.Vswitch
	// +kubebuilder:validation:Optional
	PodVswitchIds []*string `json:"podVswitchIds,omitempty" tf:"pod_vswitch_ids,omitempty"`

	// References to Vswitch in vpc to populate podVswitchIds.
	// +kubebuilder:validation:Optional
	PodVswitchIdsRefs []v1.NamespacedReference `json:"podVswitchIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Vswitch in vpc to populate podVswitchIds.
	// +kubebuilder:validation:Optional
	PodVswitchIdsSelector *v1.NamespacedSelector `json:"podVswitchIdsSelector,omitempty" tf:"-"`

	// kube-proxy proxy mode. Default: ipvs. Options: iptables, ipvs, nftables.
	// +kubebuilder:validation:Optional
	ProxyMode *string `json:"proxyMode,omitempty" tf:"proxy_mode,omitempty"`

	// RDS instance list, You can choose which RDS instances whitelist to add instances to.
	// +kubebuilder:validation:Optional
	RDSInstances []*string `json:"rdsInstances,omitempty" tf:"rds_instances,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Resources that are automatically created during cluster creation, including NAT gateways, SNAT rules, SLB instances, and RAM Role, will be deleted. Resources that are manually created after you create the cluster, such as SLB instances for Services, will also be deleted. If you need to retain resources, please configure with retain_resources. There are several aspects to pay attention to when using retain_resources to retain resources.
	// +kubebuilder:validation:Optional
	RetainResources []*string `json:"retainResources,omitempty" tf:"retain_resources,omitempty"`

	// A list of runtime containers. If you select another container runtime, see How do I select between Docker and Sandboxed-Container. See runtime below.
	// +kubebuilder:validation:Optional
	Runtime []KubernetesRuntimeParameters `json:"runtime,omitempty" tf:"runtime,omitempty"`

	// The ID of the security group to which the ECS instances in the cluster belong. If it is not specified, a new Security group will be built.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-alibabacloud/apis/namespaced/ecs/v1alpha1.SecurityGroup
	// +kubebuilder:validation:Optional
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// Reference to a SecurityGroup in ecs to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDRef *v1.NamespacedReference `json:"securityGroupIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in ecs to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDSelector *v1.NamespacedSelector `json:"securityGroupIdSelector,omitempty" tf:"-"`

	// The issuer of the Service Account token for Service Account Token Volume Projection, corresponds to the iss field in the token payload. Set this to "https://kubernetes.default.svc" to enable the Token Volume Projection feature (requires specifying api_audiences as well). From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	// +kubebuilder:validation:Optional
	ServiceAccountIssuer *string `json:"serviceAccountIssuer,omitempty" tf:"service_account_issuer,omitempty"`

	// The CIDR block for the service network. It cannot be duplicated with the VPC CIDR and CIDR used by Kubernetes cluster in VPC, cannot be modified after creation.
	// +kubebuilder:validation:Optional
	ServiceCidr *string `json:"serviceCidr,omitempty" tf:"service_cidr,omitempty"`

	// Configure whether to save certificate authority data for your cluster to attribute certificate_authority.For cluster security, recommended configuration as true. Will be removed with attribute certificate_authority removed.
	// +kubebuilder:validation:Optional
	SkipSetCertificateAuthority *bool `json:"skipSetCertificateAuthority,omitempty" tf:"skip_set_certificate_authority,omitempty"`

	// Whether to create internet load balancer for API Server. Default to true. Only works for Create Operation.
	// +kubebuilder:validation:Optional
	SlbInternetEnabled *bool `json:"slbInternetEnabled,omitempty" tf:"slb_internet_enabled,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// When you create a cluster, set the time zones for the Master and Worker nodes. You can only change the managed node time zone if you create a cluster. Once the cluster is created, you can only change the time zone of the Worker node.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The path of customized CA cert, you can use this CA to sign client certs to connect your cluster.
	// +kubebuilder:validation:Optional
	UserCA *string `json:"userCa,omitempty" tf:"user_ca,omitempty"`

	// Desired Kubernetes version. If you do not specify a value, the latest available version at resource creation is used and no upgrades will occur except you set a higher version number. The value must be configured and increased to upgrade the version when desired. Downgrades are not supported by ACK.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KubernetesRuntimeInitParameters struct {

	// The name of the runtime. Supported runtimes can be queried by data source alicloud_cs_kubernetes_version.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The version of the runtime.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KubernetesRuntimeObservation struct {

	// The name of the runtime. Supported runtimes can be queried by data source alicloud_cs_kubernetes_version.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The version of the runtime.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KubernetesRuntimeParameters struct {

	// The name of the runtime. Supported runtimes can be queried by data source alicloud_cs_kubernetes_version.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The version of the runtime.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type MasterNodesInitParameters struct {
}

type MasterNodesObservation struct {

	// The id of a node.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of a node.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The private ip of a node.
	PrivateIP *string `json:"privateIp,omitempty" tf:"private_ip,omitempty"`
}

type MasterNodesParameters struct {
}

// KubernetesSpec defines the desired state of Kubernetes
type KubernetesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            KubernetesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KubernetesInitParameters `json:"initProvider,omitempty"`
}

// KubernetesStatus defines the observed state of Kubernetes.
type KubernetesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KubernetesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Kubernetes is the Schema for the Kubernetess API. Provides a Alicloud resource to manage container kubernetes cluster.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,alibabacloud}
type Kubernetes struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.masterInstanceTypes) || (has(self.initProvider) && has(self.initProvider.masterInstanceTypes))",message="spec.forProvider.masterInstanceTypes is a required parameter"
	Spec   KubernetesSpec   `json:"spec"`
	Status KubernetesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KubernetesList contains a list of Kubernetess
type KubernetesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Kubernetes `json:"items"`
}

// Repository type metadata.
var (
	Kubernetes_Kind             = "Kubernetes"
	Kubernetes_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Kubernetes_Kind}.String()
	Kubernetes_KindAPIVersion   = Kubernetes_Kind + "." + CRDGroupVersion.String()
	Kubernetes_GroupVersionKind = CRDGroupVersion.WithKind(Kubernetes_Kind)
)

func init() {
	SchemeBuilder.Register(&Kubernetes{}, &KubernetesList{})
}
