apiVersion: cr.alibabacloud.crossplane.io/v1alpha1
kind: EeRepo
metadata:
  annotations:
    meta.upbound.io/example-id: cr/v1alpha1/eerepo
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    detail: this is a public repo
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    name: ${var.name}-${random_integer.default.result}
    namespaceSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: cn-beijing
    repoType: PUBLIC
    summary: this is summary of my new repo

---

apiVersion: cr.alibabacloud.crossplane.io/v1alpha1
kind: EeInstance
metadata:
  annotations:
    meta.upbound.io/example-id: cr/v1alpha1/eerepo
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    instanceName: ${var.name}-${random_integer.default.result}
    instanceType: Advanced
    paymentType: Subscription
    period: 1
    region: cn-beijing
    renewPeriod: 0
    renewalStatus: ManualRenewal

---

apiVersion: cr.alibabacloud.crossplane.io/v1alpha1
kind: EeNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: cr/v1alpha1/eerepo
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoCreate: false
    defaultVisibility: PUBLIC
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    name: ${var.name}-${random_integer.default.result}
    region: cn-beijing
