apiVersion: cr.alibabacloud.crossplane.io/v1alpha1
kind: VPCEndpointLinkedVPC
metadata:
  annotations:
    meta.upbound.io/example-id: cr/v1alpha1/vpcendpointlinkedvpc
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    enableCreateDnsRecordInPvzt: true
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    moduleName: Registry
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: cr.alibabacloud.crossplane.io/v1alpha1
kind: EeInstance
metadata:
  annotations:
    meta.upbound.io/example-id: cr/v1alpha1/vpcendpointlinkedvpc
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    instanceName: ${var.name}-${random_integer.default.result}
    instanceType: Advanced
    paymentType: Subscription
    period: 1
    region: cn-beijing
    renewPeriod: 0
    renewalStatus: ManualRenewal

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: cr/v1alpha1/vpcendpointlinkedvpc
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    region: cn-beijing
    vpcName: ${var.name}-${random_integer.default.result}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: cr/v1alpha1/vpcendpointlinkedvpc
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 10.4.0.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: ${var.name}-${random_integer.default.result}
    zoneId: ${data.alicloud_zones.default.zones.0.id}
